docs/transaction-api.md, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/outgoing_payment/lifecycle.ts, packages/backend/src/outgoing_payment/model.ts, packages/backend/src/outgoing_payment/service.test.ts, packages/backend/src/outgoing_payment/service.ts, packages/backend/src/outgoing_payment/worker.ts
- Remove outgoing payment approval step. It was previous necessary when Rafiki would auto reserve in-Rafiki user funds for an outgoing payment. Now the wallet can get user approval for fixed delivery payment before adding payment liquidity (TBD #190).
- Remove Ready payment state.
- Change Inactive payment state to Quoting.
- Related to #156
=> chore(backend): remove outgoing payment approval

packages/backend/src/accounting/accounts.ts, packages/backend/src/accounting/errors.ts, packages/backend/src/accounting/service.test.ts, packages/backend/src/accounting/service.ts, packages/backend/src/accounting/transfers.ts, packages/backend/src/accounting/utils.ts, packages/backend/src/asset/model.ts, packages/backend/src/asset/service.test.ts, packages/backend/src/asset/service.ts, packages/backend/src/connector/core/factories/account.ts, packages/backend/src/connector/core/rafiki.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/open_payments/account/model.ts, packages/backend/src/open_payments/account/service.test.ts, packages/backend/src/open_payments/invoice/model.ts, packages/backend/src/open_payments/invoice/service.test.ts, packages/backend/src/open_payments/invoice/service.ts, packages/backend/src/outgoing_payment/ilp_plugin.ts, packages/backend/src/outgoing_payment/lifecycle.ts, packages/backend/src/outgoing_payment/model.ts, packages/backend/src/outgoing_payment/service.test.ts, packages/backend/src/peer/model.ts, packages/backend/src/peer/service.test.ts, packages/backend/src/tests/accountFactory.ts
- Use asset id as liquidity account id.
- Use asset unit as settlement account id.
- Do not look up Tigerbeetle account before deposit or withdrawal.
- Remove unused `accountingService.getAccount()`
- fixes #215 
- progress towards #225 (which will benefit from polymorphic account models)
=> chore(backend): use asset id as liquidity account id

packages/backend/src/accounting/service.test.ts, packages/backend/src/accounting/service.ts, packages/backend/src/asset/model.ts, packages/backend/src/asset/service.ts, packages/backend/src/connector/core/controllers/stream.ts, packages/backend/src/connector/core/factories/account.ts, packages/backend/src/connector/core/factories/rafiki-services.ts, packages/backend/src/connector/core/middleware/account.ts, packages/backend/src/connector/core/middleware/balance.ts, packages/backend/src/connector/core/rafiki.ts, packages/backend/src/connector/core/test/middleware/account-middleware.test.ts, packages/backend/src/connector/core/test/middleware/balance-middleware.test.ts, packages/backend/src/open_payments/account/model.ts, packages/backend/src/open_payments/account/service.ts, packages/backend/src/open_payments/invoice/model.ts, packages/backend/src/open_payments/invoice/service.ts, packages/backend/src/outgoing_payment/ilp_plugin.ts, packages/backend/src/outgoing_payment/model.ts, packages/backend/src/outgoing_payment/service.ts, packages/backend/src/outgoing_payment/worker.ts, packages/backend/src/peer/model.ts, packages/backend/src/peer/service.ts, packages/backend/src/shared/baseModel.ts, packages/backend/src/tests/accountFactory.ts
- Use model instances directly as connector accounts
- Make model class definitions explicit about implementing `ConnectorAccount` and/or `LiquidityAccount`
- setup for #225 and #220
=> chore(backend): add polymorphic ConnectorAccount interface

.github/workflows/label.yml
- Changed `pull_request` to `pull_request_target` for labeling pull requests coming from forks.
- fixes #277.
- Current labeler workflow fails when a pull request comes from a fork as you can see from [this PR](https://github.com/interledger/rafiki/pull/250).
- `pull_request_target` workflow trigger additionally gives PR author write permissions compared to `pull_request` trigger. It provides the workflow to tag pull requests coming from forks in this scenario, which is not possible with the `pull_request` trigger.
- Github states that misuse of `pull_request_target` may lead to insecure situations, check [this article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) for information. Unless the workflow contains malicious code apart from the labeler action …
=> fix(ci): support autolabelling pull requests from forks

packages/backend/src/connector/core/middleware/ilp-packet.ts, packages/backend/src/connector/core/services/client.ts
- set content-type to `application/octet-stream` when sending to peer
The content-type is expected to be set to `application/octet-stream` when receiving ilp-packets. This wasn't being set and caused sending to fail.
=> fix(backend): set content-type when sending ilp-packets to peer

.eslintrc.yml, jest.config.base.js
Adds `settings.react.version = "detect"` to `.eslintrc.yml` so the following warning will no longer be logged from `yarn lint`:
```plaintext
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
```
Per https://github.com/yannickcr/eslint-plugin-react#configuration, eslint-plugin-react doesn't automatically auto-detect the React version used. 
Please pardon the lack of related issue, I figured this small of a chore didn't warrant one. But I'm happy to file one if you'd prefer! 😄 
- ~[ ] Tests added/updated~
- ~[ ] Documentation added~
=> chore: auto-detect React version in .eslintrc.yml

.github/workflows/lint_test_build.yml, .github/workflows/main.yml
- Adds a check at the end of the PR Checks which can then be used in the brand protection rules to enforce that all PR Checks must pass before merging. 
- Requires auth and openapi to succeed before performing the build
- closes #422
=> chore: add a ci status check to end of workflows

packages/auth/Dockerfile, packages/auth/package.json, packages/backend/Dockerfile, packages/backend/README.md, packages/backend/package.json, packages/mock-account-provider/Dockerfile, packages/openapi/README.md, packages/rates/Dockerfile
- Fixes the docs to show `--filter` instead of `-F` for pnpm since `-F` is only supported in 7.9.4 of pnpm. 
- See: https://github.com/pnpm/pnpm/commit/3ac748aab5a5e849a872c5a085715d2fb508ad37
=> fix: change pnpm docs to not show -F since it does not work

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/routes.ts, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/routes.ts
- Modifies the implementation of `continueGrant` to look for a parameter named `id` instead of `continueId`
- During debugging it was noticed that the parameter value of the `continueGrant` method was not being found
- At runtime, the property name is `id` (which matches the spec) but the function was expecting it to be named `continueId`
=> feat(auth): match dereferenced name with spec name

packages/auth/src/signature/service.ts
- Runs `await` on any `next()` calls in the middleware so that it doesn't prematurely return data.
Since the `httpsig` middleware wasn't awaiting `next()`, the AS was pretty much always sending along the wrong status before the main handler for a route executed.
=> fix(auth): await next() calls in httpsig middleware

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml, packages/mock-account-provider/app/routes/keys.$keyId.ts
- use correct `AUTH_SERVER_INTROSPECTION_URL`
- update mock-account-provider key format.
- token introspection requests are still failing due to backend not including httpsig in the request
- related to #574
=> fix(map): use correct AUTH_SERVER_INTROSPECTION_URL

README.md, infrastructure/local/docker-compose.yml, packages/auth/docker-compose.yml, packages/backend/docker-compose.yml, packages/backend/jest.setup.js
Pin redis to a spefic version. 
Rafiki seems to use some new features, so some tests fails if the local machine has an older version of redis.
=> chore: pin redis to specific version

packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/incoming_payment.test.ts, packages/backend/src/graphql/resolvers/incoming_payment.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/schema.graphql, packages/mock-account-provider/generated/graphql.ts
- Added createIncomingPayment functionality
- Added tests for the new feature
- fixes #580
=> feat: added createIncomingPayment functionality for GraphQL

docs/transaction-api.md, packages/mock-account-provider/app/lib/accounts.server.ts, packages/mock-account-provider/app/routes/webhooks.ts
- Adding `incoming_payment.expired` webhook support for the mock account provider. As per webhook [docs](https://github.com/interledger/rafiki/blob/main/docs/transaction-api.md#incoming_paymentexpired), incoming payment expiry should be treated the same as completion on incoming payment (credit the account for the amount, call `WithdrawLiquidity` mutation)
- Fixes #659 :
Took this issue on after a discussion with @wilsonianb in another: [one](https://github.com/interledger/rafiki/issues/649#issuecomment-1268821849)
=> feat(MAP): support for incoming payment expiry webhook

packages/backend/package.json, packages/backend/src/open_payments/client/service.ts, pnpm-lock.yaml
=> fix(backend): do not import (nonexistent) test code

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/accessToken/service.ts
- When determining if an access token has expired or not, convert the bound `expiresIn` value to milliseconds.
Javascript `Date` handles time in milliseconds, GNAP handles time in seconds. Conversion is necessary.
=> fix(auth): use milliseconds when determining access token expiration

packages/backend/src/open_payments/client/service.test.ts, packages/backend/src/open_payments/client/service.ts, packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/open_payments/quote/service.ts
- In cases where the receiver is an incoming payment it wouldn't make sense for the quotation's expiration to be set past the expiration date of the incoming payment.
- Fixes #593
=> chore: quote expiration cannot be set past the receiver's expiration

packages/auth/src/accessToken/routes.ts, packages/auth/src/signature/middleware.test.ts, packages/auth/src/signature/middleware.ts
- Don't check for `Content-Digest` if the body object is empty.
Even if a body was not provided in the request, koa will default to an empty object.
=> fix(auth): do not check for content-digest in signature if body is empty

.github/workflows/lint_test_build.yml, packages/auth/openapi/id-provider.yaml, packages/auth/openapi/resource-server.yaml
- add validation for the OpenAPI specs to GitHub Actions
- fixes #724
=> chore: add validation for the OpenAPI specs to GitHub Actions

packages/mock-account-provider/app/lib/requesters.ts, packages/mock-account-provider/app/lib/transactions.server.ts, packages/mock-account-provider/app/routes/accounts.$accountId.tsx, packages/mock-account-provider/app/routes/index.tsx, packages/mock-account-provider/app/routes/webhooks.ts
- add `/accounts/{accountId}` page with incoming and outgoing account transactions to mock account provider
- as is, payments are queried via the admin api and not stored by the mock account provider (which makes it difficult to pre-seed transactions...)
- fixes #717
=> feat(map): display account transactions

packages/auth/src/app.ts, packages/auth/src/signature/middleware.test.ts, packages/auth/src/signature/middleware.ts
- 
Conditionally adds httpsig middleware depending on the setting of the env variable for bypassing httpsig validation.
This conditional used to be in the code but refactors of `app.ts` have caused it to be removed.
=> feat(auth): fix httpsig bypass env

packages/backend/src/config/app.ts, packages/backend/src/open_payments/auth/middleware.ts
- bypass sig validation using same flag as auth server (see #735)
=> feat(backend): bypass sig validation

infrastructure/local/peer-docker-compose.yml, packages/auth/src/config/app.ts, packages/auth/src/grant/routes.ts
- Adds a missing `/` to the `continue` field in a grant response.
- Updates the port used by the `peer-auth` container to use 4006.
- Updates the default domain config to use the configured port.
=> fix(auth): use correct port for peer-auth instance

packages/backend/src/index.ts, packages/backend/src/session/service.test.ts
- 
Fixes the following:
```
local-peer-backend-1  | {"level":40,"time":1668111855459,"pid":1,"hostname":"1cdf891dad52","service":"ConnectorService","totalReceived":2000,"err":null,"err2":null,"msg":"error incrementing stream totalReceived"}
```
See:
https://luin.github.io/ioredis/interfaces/CommonRedisOptions.html#stringNumbers
https://github.com/interledger/rafiki/blob/0c5fd38295bb7c8e5a6a4cda690b2477e834483a/packages/backend/src/connector/core/controllers/stream.ts#L34-L55
https://github.com/interledger/rafiki/blob/0c5fd38295bb7c8e5a6a4cda690b2477e834483a/packages/backend/src/connector/core/factories/rafiki-services.ts#L57-L61
=> fix(backend): enable Redis stringNumbers

packages/backend/src/connector/core/middleware/account.ts, packages/backend/src/connector/core/test/middleware/account-middleware.test.ts
- Allow a disabled (completed/expired) incoming payment to be the stream destination "outgoing" account in the connector when handling a zero-amount packet.
- fixes https://github.com/interledger/rafiki/issues/337
- resolves:
```
local-peer-backend-1  | {"level":20,"time":1668111855568,"pid":1,"hostname":"1cdf891dad52","service":"ConnectorService","err":{"type":"UnreachableError","message":"destination account is disabled","stack":"UnreachableError: destination account is disabled\n    at getAccountByDestinationAddress (/workspace/packages/backend/dist/connector/core/middleware/account.js:38:31)\n    at async account (/workspace/packages/backend/dist/connector/core/middleware/account.js:69:33)\n    at async /workspace/packages/backend/dist/connector/core/middleware/stream-address.js:9:9\n …
```
=> fix(backend): don't reject ConnectionClose packet

packages/backend/src/open_payments/payment/outgoing/routes.test.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts
- A quote can only be used for a single outgoing payment. This is enforced by using the quote id (uuid) as the outgoing payment id. This PR makes `outgoingPaymentService.create` return `OutgoingPaymentError.InvalidQuote` if there is already an existing outgoing payment with the specified `quoteId`.
- fixes #471
=> fix(backend): check that outgoing payment quote is unused

packages/backend/src/app.ts, packages/backend/src/config/app.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment_pointer/middleware.test.ts, packages/backend/src/open_payments/payment_pointer/middleware.ts, packages/backend/src/paymentPointerKey/routes.test.ts, packages/backend/src/paymentPointerKey/routes.ts, packages/backend/src/tests/app.ts, packages/open-payments/src/client/grant.ts, packages/open-payments/src/client/index.ts, packages/open-payments/src/client/requests.ts
- Configure the RS's client payment pointer and serve its jwk (derived from the configured private key)
- progress toward #583
=> feat(backend): serve jwks.json from client payment pointer

packages/auth/scripts/get-op-schema.sh, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/routes.ts, packages/open-payments/src/config.ts, packages/open-payments/src/generated/auth-server-types.ts, packages/open-payments/src/generated/resource-server-types.ts
=> fix(auth): use expires_in in grant initiation response body

packages/open-payments/src/index.ts, packages/open-payments/src/jwk.test.ts, packages/open-payments/src/jwk.ts
- Adding `generateJwk` function to `open-payments` package, to generate JWKs from given/generated key with the correct format & type for Open Payments API
Initially, this was supposed to be used in the MAP for seeding:
https://github.com/interledger/rafiki/pull/786#discussion_r1030894851
but for now, just placing this in here for any consumers to use, like @wilsonianb 's PR: https://github.com/interledger/rafiki/pull/779/files
=> feat(open-payments): generateJwk

packages/auth/package.json, packages/auth/src/signature/middleware.test.ts, packages/auth/src/signature/middleware.ts, packages/auth/src/tests/signature.ts, packages/open-payments/package.json, packages/open-payments/src/client/requests.test.ts, packages/open-payments/src/client/requests.ts, packages/open-payments/src/client/signatures.ts, pnpm-lock.yaml
- Adds Content-Digest generation to `open-payments`
- Adds Content-Digest verification to `auth`
- Closes #655.
- fixes https://github.com/interledger/rafiki/issues/755
=> feat(auth): validate content-digest header

packages/auth/src/tests/context.ts, packages/auth/src/tests/signature.ts
-  Adds `Content-Type` and `Content-Length` to the signature input & signature components of a generated httpsig signature.
- Closes #713
=> feat(auth): add content type and length to signature headers

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/routes.ts, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/routes.ts, packages/auth/src/openapi/id-provider.yaml
- Adds 40X responses to the endpoints the AS extends for interactions
- Uses `ctx.throw` for all known errors.
In order to surface certain errors properly, the needed to be reflected in the spec so that they wouldn't be swallowed by the validator.
=> feat(auth): use ctx.throw, add 40X responses to idp spec

packages/auth/src/grant/routes.test.ts, packages/auth/src/tests/context.ts
- Tests that `clientName` and `clientUri` are passed in the redirect that's made when an interaction is started.
Closes #842.
=> fix(auth): test that client info is passed along when interaction is started

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/routes.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/accessToken/service.ts, packages/auth/src/app.ts, packages/auth/src/config/app.ts, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/routes.ts, packages/auth/src/grant/service.ts, packages/auth/src/index.ts
- Checks the token value during revocation and rotation.
- Adds some in-line issues in the comments.
Closes #832.
When rotating and revoking a token, the provided management id in the URL was used to retrieve the token, but the token value that's provided during these requests wasn't being verified against the token that was retrieved.
Also, some TODOs did not have an associated Github issue attached to them. These have been created and their URIs have been added to the original associted in-line comments.
=> feat(auth): check that token value matches during rotation & revocation

docs/deployment.md, localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml, packages/auth/README.md, packages/auth/src/app.ts, packages/auth/src/config/app.ts, packages/auth/src/index.ts, packages/auth/src/tests/app.ts, packages/backend/src/config/app.ts
- move token introspection endpoint to its own server
- does not have to be open port since it is run together with auth server and backend server
- updated localenv accordingly
- fixes #1021
=> feat(auth): move introspection endpoint to its own server

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml
Previously, when running `pnpm localenv:compose build`, we would build e.g. `rafiki-cloud-nine-backend` and `rafiki-happy-life-backend`, but the images are both the same, namely the backend images. 
I added image names a la `image: rafiki-backend` to the compose files such that the images are only built once.
=> fix(localenv): add image names to build only once per compose file

packages/backend/src/open_payments/payment/incoming_remote/service.ts
- Make sure `externalRef` and `description` are undefined if missing
When trying to make a `createReceiver` GraphQL API call with the following input:
```json
{
"input": {
"description": null,
"externalRef": null,
"incomingAmount": {
"assetCode": "USD",
"assetScale": 2,
"value": 100
},
"paymentPointerUrl": "https://happy-life-bank-backend/accounts/pfry"
}
}
```
results in 
```json
{
"data": {
"createReceiver": {
"code": "500",
"message": "invalid remote incoming payment request",
"receiver": null,
"success": false
}
}
}
```
This is because the Open Payments OpenAPI spec doesn't accept "null" as a valid value when making the request (to the external Rafiki instance via the Open Payments client), and thus, the OpenAPI validation fails on the response. This PR makes sure we pass in …
=> chore: update incoming payment creation payload

localenv/mock-account-servicing-entity/app/routes/rates.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/open_payments/quote/service.ts, packages/backend/src/openapi/exchange-rates.yaml, packages/backend/src/rates/service.ts, packages/backend/src/rates/util.test.ts, packages/backend/src/rates/util.ts
- Making sure rates service can handle different exchange rates with multiple decimal points: before, there would be a bug where the currency conversion would fail because BigInt could not support decimal place results that would arise from exchange rates with more decimals than the assetScale
- Adding `base` parameter to `/rates`, updating MASE to properly return with the `base` param
- Fixes #1524
=> feat: add base parameter to /rates API

packages/backend/migrations/20210422134422_create_events_table.js, packages/backend/migrations/20211012172409_create_payment_pointers_table.js, packages/backend/migrations/20230629094019_drop_events_table.js, packages/backend/migrations/20230629094400_add_deactivatedat_payment_pointers.js
In order to make sure there are no breaking changes when updating to the new version of `backend` Rafiki, this PR updates the backend postgres migrations that have been released to `main` since `v1.0.0-alpha.1` tag. This includes:
- adding a new migration to drop the `events` table (instead of deleting `create_events_table` migration file)
- adding `deactivatedAt` to `paymentPointers` in a separate migration (instead of editing the `create_payment_pointers_table` migration)
=> chore: fix migrations

packages/backend/src/open_payments/payment_pointer/middleware.ts, packages/backend/src/open_payments/payment_pointer/service.test.ts, packages/backend/src/open_payments/payment_pointer/service.ts
The function `paymentPointerService.getByUrl` was used in the remoteIncomingPayment service, when getting or creating a local or remote incoming payment, in order to determine whether the payment pointer URL provided was or wasn't a local payment pointer. This means, whenever we call "get receiver" or "create receiver", we end up having to wait  for the function to poll for the payment pointer at the ASE. This adds a lot of extra overhead for cases where often, the receiver in question is at at another, remote Rafiki instance. I believe we should only end up polling for the payment pointer during open payments calls: meaning, only in the payment pointer middleware. 
- Related to #1501
=> feat: only poll for payment pointers in the open payments middleware

infrastructure/helm/tigerbeetle/values.yaml, jest.config.base.js, localenv/tigerbeetle/docker-compose.yml, packages/auth/src/grant/service.test.ts, packages/auth/src/graphql/resolvers/grant.test.ts, packages/auth/src/tests/grant.ts, packages/backend/package.json, packages/backend/src/tests/tigerbeetle.ts, pnpm-lock.yaml
- Update grant pagination tests 
- (hopefully) fix BigInt serialization issue during test running
- upgrade tigerbeetle to 0.13.38
Sometimes, we would see this test failure in the CI step, [example](https://github.com/interledger/rafiki/actions/runs/5455836801/jobs/9927874921):
```js
FAIL auth src/grant/service.test.ts
● Grant Service › getGrantsPage › Can paginate and filter
TypeError: Cannot read properties of undefined (reading 'id')
324 |       )
325 |
> 326 |       expect(page[0].id).toBe(grants?.[1].id)
|                      ^
327 |       expect(page.length).toBe(1)
328 |     })
329 |   })
at Object.id (packages/auth/src/grant/service.test.ts:326:[22](https://github.com/interledger/rafiki/actions/runs/5455836801/jobs/9927874921#step:5:23))
```
This is because of the `Promise.all`: …
=> chore: update sporadically failing tests, upgrade tigerbeetle

infrastructure/helm/tigerbeetle/values.yaml, packages/backend/src/shared/baseModel.ts
- _Should_ fix some sporadic tests failures for pagination
- Sets proper image for tigerbeetle in helm chart (after #1541)
Sometimes, we would get webhook event pagination tests failures such as:
```js
FAIL backend src/graphql/resolvers/webhooks.test.ts
● Webhook Events Query › Common query resolver pagination › pageInfo is correct on pagination from middle
expect(received).toEqual(expected) // deep equality
Expected: "d86328d9-aaa4-4435-9109-d127a6db63b4"
Received: "598ebaff-2fef-4e57-9226-7eed8d76[75](https://github.com/interledger/rafiki/actions/runs/5474725660/jobs/9969921725#step:5:76)db"
212 |       expect(query.pageInfo.hasPreviousPage).toBeTruthy()
213 |       expect(query.pageInfo.startCursor).toEqual(models[20].id)
> 214 | …
```
=> chore: fix timestamp-related tests failures

packages/backend/src/middleware/cache/data-stores/in-memory.test.ts, packages/backend/src/middleware/cache/data-stores/in-memory.ts, packages/backend/src/middleware/cache/data-stores/index.ts, packages/backend/src/middleware/cache/data-stores/redis.test.ts, packages/backend/src/middleware/cache/data-stores/redis.ts, packages/backend/src/middleware/cache/index.test.ts, packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/open_payments/quote/service.ts, packages/backend/src/rates/service.test.ts, packages/backend/src/rates/service.ts
In a discussion with @raducristianpopa, he noticed 
1. we should be using the sending asset code as base rate when creating the quote, instead of (incorrectly) the receiving asset code, and
2. Now that we are using a base rate when asking for rates from the ASE, the rates service caching does not take into account different possible base's. This means when we request rates with base USD, we cache the result, and will continue return USD even if we ask for EUR as base rate. 
This change:
- uses the sending asset code as base rate when creating a quote
- adds in-memory caching as a data store
- updates rate service to use in-memory caching data store & take into account base rate when caching & returning rates
Fixes #1676
=> fix: use sending asset for base rate when creating quote

packages/documentation/astro.config.mjs, packages/documentation/public/scripts.js
- This PR adds a `MutationObserver` which checks for `aria-current` changes in the ToC then scrolls new active links into view.
Closes #1781
=> fix: add mutation observer for long ToC

packages/backend/src/app.ts, packages/backend/src/asset/service.test.ts, packages/backend/src/asset/service.ts, packages/backend/src/auto-peering/routes.test.ts, packages/backend/src/auto-peering/routes.ts, packages/backend/src/auto-peering/service.test.ts, packages/backend/src/auto-peering/service.ts, packages/backend/src/config/app.ts, packages/backend/src/index.ts
- Adding auto peering server (default port 3005)
- Adding auto peering service & routes that return ilpAddress as well as list of supported assets
Start of auto-peering story. Adding GET route for returning peering details (for peering discoverability). The new server instantiation itself is under a flag (defaults OFF)
Fixes #1763
=> feat: get peering details

localenv/happy-life-bank/docker-compose.yml
With these changes, on a clean localenv start-up we will only build the local images once.
Total time spent executing `pnpm localenv:compose up -d`:
- branch `main`: 6.68s user 8.89s system 9% cpu 2:37.82 total
- branch `rp--localenv-docker-images` 4.45s user 5.88s system 6% cpu 2:27.95 total
Despite the fact that all `happy-life-bank` services rely on those of `cloud-nine-wallet`, it does not impact the execution time. The 10s difference might be due to some network delays during image building/pulling.
- closes #1811
=> chore: build images once

packages/backend/src/open_payments/payment_pointer/key/service.test.ts, packages/backend/src/open_payments/payment_pointer/key/service.ts
- When fetching payment pointer keys only non-revoked keys are returned
- fixes #1760
=> feat: fetching retrieves non-revoked keys for a payment pointer

packages/auth/src/app.ts, packages/auth/src/index.ts, packages/auth/src/signature/middleware.test.ts, packages/auth/src/tests/context.ts, packages/backend/src/app.ts, packages/backend/src/index.ts, packages/backend/src/shared/ilp_plugin.ts, packages/backend/src/tests/context.ts
- Moves ILP connector server into app, instead of having it separately defined in `index.ts`
- Updates `app.shutdown` function to properly close all running servers (in both `auth` and `backend` packages)
- Make sure we are correctly handling multiple SIGTERM events
- Remove unused `closeEmitter`
Related to: https://github.com/interledger/rafiki/pull/1805#discussion_r1313026526
=> refactor: update shutdown process

README.md, localenv/README.md
Update the docs links to point at rafiki.dev
fixes #1835
Docs got moved to the rafiki.dev website, readme left outdated.
=> fix(docs):  Update readme links

packages/auth/package.json, packages/backend/package.json, packages/token-introspection/package.json
- adds command to run tests and show coverage for files that jest thinks have changed or were related to changes since main
Closes: https://github.com/interledger/rafiki/discussions/1821
Allows us to get current coverage of tests, but does not show any difference between current branch coverage and main.
If you're really motivated to show the difference from main, you can generate a summary on main and the base branch and run this command: 
pnpx cov-diff coverage-summary1.json coverage-summary2.json
Not sure if that will prove useful but thought I'd share. https://www.npmjs.com/package/cov-diff
=> feat: add test coverage commands

packages/auth/src/interaction/routes.test.ts, packages/auth/src/interaction/routes.ts
- Encodes the Grant Request endpoint in the post-interaction hash rather than the interaction redirect URI.
Fixes #1898.
Somehow I didn't catch that the wrong URI was being encoded in the post-interaction hash.
=> fix(auth): hash the correct url when interaction ends

packages/auth/src/interaction/routes.test.ts, packages/auth/src/interaction/routes.ts
- Updates the hashing method for the post-interaction hash to use `sha-256` instead of `sha3-512`.
Fixes #1900.
Rafiki's original implentation of GNAP was based on version 11, which used `sha3-512` as a default hashing method for the post-interaction hash. The current version of GNAP (15) uses `sha-256` as the default.
=> feat(auth): update interaction hash method

packages/backend/src/app.ts
- Instead of using a "magic for-loop", the backend app now mounts each resource server route explicitly.
Fixes #916.
It has been pointed out that the for loop that is used to mount resource server routes onto the backend app isn't very readable. In the interest of code readability, this has been refactored to mount each route explicitly, so it's easy to understand what routes the backend extends.
=> feat(backend): mount resource server routes explicitly

localenv/mock-account-servicing-entity/app/lib/webhooks.server.ts, localenv/mock-account-servicing-entity/app/routes/webhooks.ts, packages/frontend/app/shared/enums.ts
- Getting webhook event enums in sync between frontend and the mock account servicing entity
=> fix: re-aligning both webhook type enum definitions

packages/backend/migrations/20230918113102_rename_payment_pointer_tables.js, packages/backend/src/graphql/resolvers/combined_payments.test.ts, packages/backend/src/graphql/resolvers/combined_payments.ts, packages/backend/src/graphql/resolvers/incoming_payment.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/resolvers/quote.ts, packages/backend/src/open_payments/payment/combined/model.ts, packages/backend/src/open_payments/payment/incoming/model.ts, packages/backend/src/open_payments/payment/incoming/service.ts, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/open_payments/payment_pointer/key/model.ts, packages/backend/src/open_payments/payment_pointer/model.ts, packages/backend/src/open_payments/quote/model.ts, packages/backend/src/open_payments/quote/service.ts, packages/backend/src/tests/combinedPayment.ts, packages/backend/src/tests/quote.ts
- Rename all tables & columns that refer to 'payment pointers' to refer to 'wallet addresses' instead.
Fixes #1934.
=> feat(backend): rename "payment pointer" tables & columns to use "wallet address"

packages/backend/src/payment-method/handler/errors.ts, packages/backend/src/payment-method/handler/service.test.ts, packages/backend/src/payment-method/handler/service.ts, packages/backend/src/payment-method/ilp/service.test.ts, packages/backend/src/payment-method/ilp/service.ts, packages/backend/src/tests/outgoingPayment.ts, packages/backend/src/tests/quote.ts
This PR adds `pay` method support to the `ilpPaymentService`. This PR is basically prepping the service to be used during the lifecycle of an Outgoing Payment (stay tuned shortly), to abstract out all of the ILP pay stuff, so the outgoingPayment lifecycle is payment method agnostic:
https://github.com/interledger/rafiki/blob/c16a60fdfa10563998ffc26ea3b669109a98fe15/packages/backend/src/open_payments/payment/outgoing/lifecycle.ts#L91-L131
It also introduces `PaymentMethodHandlerError` error class that will be used to signify details about a thrown error during the `paymentMethodHandler.pay` and  `paymentMethodHandler.startQuote` methods, so the caller can react according, for example, whether it is safe to retry the payment/quote or not.
Progress towards #1967
=> feat: add pay method to ilpPaymentService

packages/backend/migrations/20230927223235_make_quotes_generic.js, packages/backend/src/open_payments/quote/model.ts, packages/backend/src/open_payments/quote/service.ts
- There is an issue in the `packages/backend/migrations/20230927223235_make_quotes_generic.js` migration if there is existing data, when trying to create a non-nullable `estimatedExchangeRate`. Fixing to `estimatedExchangeRate` in table to be nullable until https://github.com/interledger/rafiki/issues/2000 is being worked on
Related to #1967
=> chore: make estimatedExchangeRate nullable (for now)

openapi/auth-server.yaml, openapi/resource-server.yaml, openapi/schemas.yaml, packages/backend/src/app.ts, packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/middleware.ts, packages/backend/src/open_payments/payment/incoming/model.ts, packages/backend/src/open_payments/payment/incoming/routes.test.ts, packages/backend/src/open_payments/payment/incoming/routes.ts, packages/backend/src/open_payments/wallet_address/model.test.ts, postman/collections/Interledger.json
- remove connections route from open payments spec
- remove connections route and any associated service functions
from backend
- 
This is the same as https://github.com/interledger/rafiki/pull/1940, but with some rebasing work.
Somehow, during the maintenance of nl-open-payments to be kept up to date with main, this commit was lost. This PR will re-introduce the changes.
(Re-)Fixes https://github.com/interledger/rafiki/issues/1910
=> feat(backend): unauthenticated get incoming payment (#1952)

packages/backend/src/open_payments/payment/outgoing/lifecycle.ts
Fixing
```
pnpm build
> @interledger/rafiki@1.0.0-alpha.3 build /Users/sabine/git/coil/rafiki
> tsc --build
packages/backend/src/open_payments/payment/outgoing/lifecycle.ts:98:43 - error TS18048: 'payment.quote.estimatedExchangeRate' is possibly 'undefined'.
98     Math.ceil(Number(alreadySentAmount) * payment.quote.estimatedExchangeRate)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
 ELIFECYCLE  Command failed with exit code 2.
```
=> fix: fallback in case estimated exchange rate is missing

packages/auth/src/accessToken/service.test.ts, packages/auth/src/signature/middleware.test.ts
- Expect `Grant` object to be included with `AccessToken` when it is retrieved from the database in tests.
Possibly due to a package update from `objectionjs`, as the `pnpm-lock` file has been updated recently, queries for `AccessToken` from the access token service include the `Grant` model which wasn't accounted for in the tests.  
=> feat(auth): fix auth tests for access tokens

packages/backend/src/graphql/resolvers/combined_payments.test.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/combined/service.test.ts, packages/backend/src/open_payments/payment/outgoing/routes.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/payment-method/handler/service.test.ts, packages/backend/src/payment-method/ilp/service.test.ts, packages/backend/src/shared/pagination.test.ts, packages/backend/src/tests/combinedPayment.ts, packages/backend/src/tests/outgoingPayment.ts
- Reconciles some stuff that broke when rebasing `nl-open-payments` on main.
Rebasing `nl-open-payments` on main caused some things surrounding removing connections and adding the payment method handler that this PR will hopefully reconcile.
=> fix(backend): resolve breaking build after main rebase

packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/tests/outgoingPayment.ts
- fixes combined payment tests. the combined payments are a view of both incoming and outgoing payments and the new createOutgoingPayment test util function now creates an incoming payment too (after removing connections). This side effect caused the pagination and some other tests to fail which didn’t expect this additional payment.
- fix how we are generating stream credentials in `createOutgoingPaymentWithReceiver`
- fixes #2081 
- progress towards #2074
=> fix(backend): combined_payment, ilp service tests

packages/backend/src/open_payments/payment/incoming/routes.test.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/open_payments/quote/service.ts, packages/backend/src/open_payments/wallet_address/model.test.ts, packages/backend/src/tests/quote.ts
- Fetches the `walletAddress` graph when creating or reading Quotes or Outgoing Payments.
- Fixes some tests in the Outgoing Payments and Quotes services/routes.
Makes progress on #2074.
=> fix: fetch walletAddress graph in quote and outgoing payment service

packages/backend/src/open_payments/payment/incoming_remote/service.test.ts, packages/backend/src/open_payments/payment/incoming_remote/service.ts
- Updates the remote incoming payment service's call to the Open Payments client to use the domain of the wallet URL it receives, rather than the full wallet address.
Fixes #2117.
When creating a remote receiver, Rafiki would try to send the full wallet address into a call of `openPaymentsClient.incomingPayment.create`. Because of the way the spec has changed however, meant that we were sending requests to `http://domain/walletaddress/incoming-payments` when it should have been to `http://domain/incoming-payments`.
=> fix(backend): fix create remote incoming payment

packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/middleware.ts
- Returns the `WWW-Authenticate` header on the public incoming payment response.
Fixes #2045.
Because `GET /incoming-payments` can be called without authentication and respond without at `401`, it was not being returned with a `WWW-Authenticate` header as per GNAP spec in the event of failed token introspection.
=> feat(backend): return WWW-Authenticate header in public incoming payment response

packages/backend/src/open_payments/payment/incoming/service.test.ts
- Updates the `Cannot create incoming payment with different asset details than underlying wallet address` test to shift the character codes of an asset code by one rather than reversing it.
Fixes #2112.
This test is intended to test a case where the asset code in an incoming payment creation call is discrepant with what is attached to the associated wallet address. However, because reversing the order was the strategy to create discrepancy, palindromic asset codes would produce the same asset code as the original.
=> fix(backend): prevent palindromic asset codes from causing test failure

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/combined_payments.test.ts, packages/backend/src/graphql/resolvers/incoming_payment.test.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/wallet_address.test.ts, packages/backend/src/graphql/schema.graphql, packages/frontend/app/generated/graphql.ts
- Adds the `liquidity` field to graphQL requests on `IncomingPayment`, `OutgoingPayment`, and `Payment`
Fixes #1694.
Allows liquidity for payments and wallet addresses to be displayed on the admin UI.
=> feat(backend): add liquidity to payment and wallet address resolvers

packages/backend/package.json, pnpm-lock.yaml
- upgrades backend devDependency `ilp-protocol-stream` from `^2.7.1` to `^2.7.2-alpha.2`
Renovate didn't pick it up because of the `alpha` and I noticed it because it has a very old and deprecated uuid sub dependancy that `pnpm install` warns about. It is only used in one test, hence the `devDependency`. The other ilp packages that use it under the hood are using this latest alpha version.
=> chore(backend): upgrade ilp-protocol-stream

packages/backend/src/accounting/psql/ledger-transfer/index.test.ts, packages/backend/src/accounting/psql/ledger-transfer/index.ts
After doing some testing related to the off-by-one "issue" in the ILP library, I came across an incorrect behavior of the way that POSTED transfers are looked up when using PSQL accounting. Basically, POSTED transfers with an expiry date in the past were being incorrectly ignored. This PR fixes this behaviour.
=> fix: psql transfer lookup

README.md, packages/documentation/src/content/docs/index.mdx
- This PR refines the elevator pitch of what Rafiki is.
=> chore: update README.md

packages/documentation/src/content/docs/telemetry/overview.md
optionality is now detailed in the telemetry overview docs.
fixes #1924
Note - since main rafiki readme has a more general introduction approach, a better place for the optionality is suggested in this PR -> telemetry overview docs
=> feat(telemetry): add optionality info in docs

packages/backend/src/payment-method/ilp/connector/core/test/middleware/account-middleware.test.ts
=> test(backend): add test for unknown destination account

packages/backend/src/accounting/service.ts, packages/backend/src/accounting/tigerbeetle/utils.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/open_payments/payment/incoming/service.ts, packages/backend/src/open_payments/quote/model.ts, packages/backend/src/tests/outgoingPayment.ts, packages/backend/src/tests/quote.ts, packages/mock-account-service-lib/src/account-provider.ts
- Add error messages to Error exceptions that are without messages
* fixes #2579
* had too much time on weekend and I decided that I will check some simple issues :)
=> fix(exceptions): add message to exceptions that are missing message

packages/backend/src/accounting/psql/service.ts, packages/backend/src/accounting/service.ts, packages/backend/src/accounting/tigerbeetle/service.ts, packages/backend/src/index.ts, packages/backend/src/payment-method/ilp/connector/core/factories/rafiki-services.ts, packages/backend/src/payment-method/ilp/connector/core/middleware/telemetry.ts, packages/backend/src/payment-method/ilp/connector/core/rafiki.ts, packages/backend/src/payment-method/ilp/connector/core/test/middleware/telemetry.test.ts, packages/backend/src/payment-method/ilp/connector/index.ts
This PR moves the amount metrics collection from the accounting service back to the ILP connector, as an extra middleware.
All context is provided in the linked issue
fixes #2531 #2505
if you enable telemetry on the playground containers, you should be able to see the metrics output of your transactions [here](https://rafikitelemetry.grafana.net/public-dashboards/f70c8a6033b14da5a9f1cb974def602a)
=> feat(telemetry): move amount collection in ILP connector

packages/auth/src/app.ts, packages/backend/src/app.ts
This PR sets the ignoreIntrospection flag on maxDepth for the apolloArmor to true, so that integrators can query the graphql schema with codegen tools
Rafiki.money uses a codegen tool for graphql. The tool and the GUI for apolloClient were blocked by the new security addition ApolloArmor, specifically on the depth of the queries.
We should allow deep queries on introspection
=> feat(graphql-security): support for deep graphql queries on introspection 

.github/workflows/node-build.yml
This will just update timeout value for prerequisite job in workflow.
I noticed that this job is sometime failing due to running just about 1 min so 5 minutes should be more than enough to not fail anymore
=> chore(workflows): bump prerequisite timeout from 1 to 5 minutes

packages/frontend/app/routes/payments.incoming.$incomingPaymentId.tsx, packages/frontend/app/routes/payments.outgoing.$outgoingPaymentId.tsx, packages/frontend/app/routes/peers.$peerId.tsx, packages/frontend/app/routes/peers.create.tsx, packages/frontend/app/styles/tailwind.css
- renames `tooltip` css class to `default-link`
- applies to pre-existing `a` elements that used a different method to achieve default(ish) styling
Suggestion for PR https://github.com/interledger/rafiki/pull/2716
=> refactor: standardize default a link styling

bruno/collections/Rafiki/Rafiki Admin APIs/Cancel Outgoing Payment.bru, localenv/cloud-nine-wallet/seed.yml, localenv/mock-account-servicing-entity/app/lib/webhooks.server.ts, localenv/mock-account-servicing-entity/generated/graphql.ts, localenv/mock-account-servicing-entity/seed.example.yml, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/documentation/src/content/docs/integration/event-handlers.mdx, packages/frontend/app/generated/graphql.ts, packages/frontend/app/shared/utils.ts, packages/mock-account-service-lib/src/generated/graphql.ts, test/integration/lib/generated/graphql.ts
- feat(localenv): cancel outgoing payment on created webhook
- feat(graphql): cancel outgoing payment api
- feat(outgoing-payment): cancel outgoing payment service implementation
Add an API for canceling outgoing payment. This can be possible only if outgoing payment is in funding state. Normally, this API would be called by ASE to cancel the outgoing payment. It can be canceled due too numerous reasons like account not having enough balance or like his KYC is not valid, etc. ASE can also specify cancelation reason, and it will be written in meta under cancellationReason key. 
fixes #2688
=> feat(api): cancel outgoing payment

packages/auth/package.json, packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/routes.ts, packages/auth/src/app.ts, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/routes.ts, packages/auth/src/index.ts, packages/auth/src/interaction/routes.test.ts, packages/auth/src/interaction/routes.ts, packages/auth/src/logger/service.ts, packages/auth/src/shared/gnapErrors.test.ts, packages/auth/src/shared/gnapErrors.ts, packages/auth/src/shared/utils.ts, packages/auth/src/signature/middleware.test.ts, packages/auth/src/signature/middleware.ts, pnpm-lock.yaml
- Adds logging to route handlers on the auth server
- Includes request method, path, and a unique request id in each log
- Includes a breakdown of the request body, params, and headers (that are applicable) in each log
- If applicable, any other relevant objects that were created/retrieved in the route business logic (e.g. a grant or an interaction)
Closes #2577.
=> feat(auth): add logs to routes

bruno/collections/Rafiki/Rafiki Admin APIs/Create Wallet Address.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Get Wallet Address.bru, localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/app.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/resolvers/walletAddressAdditionalProperties.ts, packages/backend/src/graphql/resolvers/wallet_address.test.ts, packages/backend/src/graphql/schema.graphql, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, test/integration/lib/generated/graphql.ts
Moves the `additionalProperties` resolver under the `WalletAddress` resolver. This allows us to query this field on wallet address as opposed to calling it separately with the wallet address id, but keeps the fetching outside of the wallet address resolver/service method itself. This means we can specify it anywhere the wallet address is returned (the get wallet address query, create wallet address mutation, etc.)
See test and bruno collection changes to see how its called.
To be merged into https://github.com/interledger/rafiki/pull/2752
=> fix: put additional properties resolver under wallet address

bruno/collections/Rafiki/Rafiki Admin Auth APIs/Get Grant.bru, bruno/collections/Rafiki/Rafiki Admin Auth APIs/Get Grants.bru, bruno/collections/Rafiki/Rafiki Admin Auth APIs/Revoke Grant.bru, bruno/collections/Rafiki/environments/Local Playground.bru, bruno/collections/Rafiki/scripts.js, localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml, packages/auth/jest.config.js, packages/auth/jest.setup.js, packages/auth/jest.teardown.js, packages/auth/package.json, packages/auth/src/app.ts, packages/auth/src/config/app.ts, packages/auth/src/shared/utils.test.ts, packages/auth/src/shared/utils.ts, packages/auth/src/tests/apiSignature.ts, pnpm-lock.yaml
- Added signature header verification to Auth Server Admin API
Closes #2704.
=> feat(auth): secure admin api with hmac signatures

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml, test/integration/testenv/cloud-nine-wallet/docker-compose.yml, test/integration/testenv/happy-life-bank/docker-compose.yml
- adds default env var, fixing local env failing to start properly
im seeing the c9 MASE fail to start in the local environment since commit d5c7860fff26c29480fcf6d63c16bb63398169c8
```
cloud-nine-mock-ase-1  | setting up from seed...
cloud-nine-mock-ase-1  | seeding failed with ApolloError: request to http://cloud-nine-wallet-backend:3001/graphql failed, reason: connect ECONNREFUSED 10.5.0.8:3001. If seeding has already completed this can probably be ignored
```
Looks like its from no longer having a default value for the `ILP_CONNECTOR_ADDRESS` in backend - setting a default in the docker compose fixes it.
=> fix(localenv): C9 MASE fail to start

packages/backend/src/open_payments/payment/outgoing/errors.ts, packages/backend/src/open_payments/quote/errors.ts, packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/open_payments/quote/service.ts, packages/backend/src/payment-method/handler/errors.ts, packages/backend/src/payment-method/ilp/service.test.ts, packages/backend/src/payment-method/ilp/service.ts
Error during quoting if the ILP quote will not fulfil at least a single unit of the receiving asset. See #2770 for detailed explanation.
Fixes #2770
=> chore(backend): estimate ILP quote receive amount, and fail early

packages/frontend/app/routes/auth.login.tsx, packages/frontend/app/routes/auth.recovery.tsx, packages/frontend/app/routes/settings.tsx
- This PR addresses a bug in the Admin UI where the settings page fails to load correctly, resulting in a 404 error. The issue arises due to the browser getting stuck at the Kratos endpoint and not following the redirect back to the settings page in the Admin UI with the flow ID appended. This bug is resolved by replacing the redirect function with redirectDocument to ensure the correct handling of document-level redirects. In the settings.tsx page I'm simply swapping `redirect` with `redirectDocument`. 
We are using a nightly build to test if this resolves issues in possible production deployments. 
- fixes #2793
=> fix: fix incorrect loading of admin ui settings page

packages/frontend/app/components/LiquidityDialog.tsx, packages/frontend/app/routes/assets.$assetId.deposit-liquidity.tsx, packages/frontend/app/routes/assets.$assetId.withdraw-liquidity.tsx, packages/frontend/app/routes/peers.$peerId.deposit-liquidity.tsx, packages/frontend/app/routes/peers.$peerId.withdraw-liquidity.tsx
- Add an asset prop in liquidity dialog component to receive the asset info.
- Get the asset info on the loader of withdraw and deposit components using the `getPeer` api method.
- Get the asset info on the loader of withdraw and deposit components using the `getAssetInfo` api method.
In the rafiki Admin UI, the liquidity information of peer and asset details are displayed using the current asset scale. When the user wants to deposit or withdraw liquidity, the amount introduced is handle using a scale of 0. So it is ambiguous on what scale the user is withdrawing or depositing.
Fixes: #2798
=> fix(frontend): It is ambiguous on what scale is the withdrawal and deposit input

packages/frontend/app/components/LiquidityDialog.tsx, packages/frontend/app/routes/assets.$assetId.tsx
- Make the `LiquidityDialog` component retains underlying page scroll position on asset page.
- Add autofocus to the input of  `LiquidityDialog` in order to improve the user experience.
This pull request resolves the #2825 issue.
=> feat(frontend): ux improvements to liquidity dialog component

localenv/mock-account-servicing-entity/Dockerfile, packages/auth/Dockerfile.dev, packages/auth/Dockerfile.prod, packages/backend/Dockerfile.dev, packages/backend/Dockerfile.prod, packages/frontend/Dockerfile.dev, packages/frontend/Dockerfile.prod
- feat(auth): build with alpine3.19
- feat(backend): build with alpine3.19
- feat(frontend): build with alpine3.19
Due to one CVE, our CI builds are failing due to some CVE that was not fixed in alpine3.18, so I decided that maybe we can bump that up a little bit. So I did an upgrade from alpine3.18 to alpine3.19
=> feat(docker): switch to alpine3.19

packages/auth/src/app.ts, packages/auth/src/interaction/routes.ts
- Fixes the `maxAge` is invalid error by changing from hget/hset (saved as redis hashmap) to set/get (string) so that we can use `JSON.parse` and `JSON.stringify`. Saving the `JSON.stringify`ied session preserves the datatypes so that we don't need to [deal with manually re-forming the session](https://github.com/interledger/rafiki/pull/2832#discussion_r1700705829) and can just do `JSON.parse` on read.
- Fixes cookie not expiring in browser by returning `null` from `get` when the session is not found.
- removes unused session middleware in interaction server (`'/grant/:id/:nonce'`, `'/grant/:id/:nonce/:choice'`)
- fixes #2826
=> fix(auth): interact redirect

packages/auth/src/interaction/routes.test.ts, packages/auth/src/interaction/routes.ts, packages/auth/src/openapi/specs/id-provider.yaml
- return grantId when doing grant lookup via interaction id
fixes #2835
=> feat(interaction): return grantId

bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Payment/Get Outgoing Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Get Outgoing Payment.bru, localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/tests/outgoingPayment.ts, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, test/integration/lib/generated/graphql.ts
- update GraphQL schema for outgoing payment to also include grantId
fixes #2836
=> feat(outgoing-payment): add grantId to admin api

packages/auth/migrations/20240802171939_add_revoked_at_to_access_tokens.js, packages/auth/src/access/service.test.ts, packages/auth/src/access/service.ts, packages/auth/src/accessToken/model.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/accessToken/service.ts, packages/auth/src/grant/service.test.ts, packages/auth/src/grant/service.ts
- Soft delete access items on grant revocation
- Soft delete access tokens on revocation & grant revocation
Fixes #2819
=> feat(auth): soft delete access tokens and grant accesses

packages/auth/src/app.ts
- Sets the `maxAge` of a `koa-session`, and by extension, session cookies, to be based off of the value of the interaction expiry environment variable.
Closes #2850
=> feat(auth): set session expiry based on interaction expiry env

localenv/telemetry/docker-compose.yml, localenv/telemetry/grafana/provisioning/dashboards/example.json, localenv/telemetry/tempo.yaml
- Configures tempo to generate metrics based off spans
- Adds visualization for 95th percentile graphql resolver durations to localenv dashboard (live dashboard not applicable because tracing is local only atm)
Visualization preview:
fixes: https://github.com/interledger/rafiki/issues/2848
=> feat(localenv): span metrics generation

bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Cross Currency Payment/Create Quote.bru, bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Payment/Create Quote.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Cancel Outgoing Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Outgoing Payment From Incoming Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Outgoing Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Quote.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Get Outgoing Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Get Quote.bru, localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/quote.test.ts, packages/backend/src/graphql/resolvers/quote.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/open_payments/quote/service.test.ts, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, test/integration/lib/admin-client.ts, test/integration/lib/generated/graphql.ts
* Remove internal fields from quote schema
fixes #2856
=> feat(quote): remove internal fields from schema

localenv/telemetry/grafana/provisioning/dashboards/example.json, packages/backend/src/fee/service.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/quote/service.ts, packages/backend/src/payment-method/ilp/service.ts, test/performance/scripts/create-outgoing-payments.js
VUs: 5
Durations: 120s
Iterations: 3113   25.914919/s
p(90)=225.94ms
```
data_received..................: 3.2 MB 27 kB/s
data_sent......................: 5.4 MB 45 kB/s
http_req_blocked...............: avg=1.88µs   min=458ns  med=1.66µs   max=427.2µs  p(90)=2.29µs   p(95)=2.54µs  
http_req_connecting............: avg=44ns     min=0s     med=0s       max=154.25µs p(90)=0s       p(95)=0s      
http_req_duration..............: avg=64.23ms  min=5.67ms med=52.18ms  max=2.15s    p(90)=111.75ms p(95)=120.94ms
{ expected_response:true }...: avg=64.23ms  min=5.67ms med=52.18ms  max=2.15s    p(90)=111.75ms p(95)=120.94ms
http_req_failed................: 0.00%  ✓ 0         ✗ 9334
http_req_receiving.............: avg=40.17µs  min=7.04µs med=39.87µs  max=638.37µs p(90)=54.69µs  p(95)=59.47µs …
```
=> feat(backend): ww performance create quote metrics

localenv/cloud-nine-wallet/dbinit.sql
=> chore(localenv): fix startup migration

packages/auth/src/access/utils.test.ts, packages/auth/src/access/utils.ts, packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/middleware.ts
Update token introspection to always pass in `identifier` instead of just during outgoing payments, this fixes an issue when doing token introspection for incoming payment grant _with_ `identifiers`
[Slack thread](https://interledgerfoundation.slack.com/archives/C05EMHTG6FM/p1724763454737309)
Fixes #2906
=> fix: always pass in `identifier` into token introspection

localenv/telemetry/grafana/provisioning/dashboards/example.json, packages/backend/src/accounting/psql/service.ts, packages/backend/src/accounting/tigerbeetle/service.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/lifecycle.ts, packages/backend/src/open_payments/receiver/service.ts, packages/backend/src/payment-method/ilp/connector/index.ts, packages/backend/src/payment-method/ilp/peer/service.ts, pnpm-lock.yaml, test/performance/scripts/create-outgoing-payments.js
=> feat(backend): add tracing, metrics, get peer tweak

.github/labeler.yml, .github/pull_request_template.md, .github/workflows/add_to_docs_board.yml
- Remove `type: documentation` auto labeller (we should be manually labelling `user-docs` issues so writers can get it on their board)
- Update auto-add-to docs-board action
- Update PR checklist
Fixes #2955
=> chore: documentation workflow updates

packages/backend/package.json, packages/backend/src/openapi/specs/webhooks.yaml
Updated the webhooks.yaml for OpenAPI by adding spec for `incomingPaymentCreated` event and for `amount` schema. Removed `postinstall` and `copy-op-schemas` from backend scripts.
- Added spec for `incomingPaymentCreated` event.
- Added spec for `amount` schema.
- Removed `postinstall` and `copy-op-schemas` scripts from `backend`.
Added missing spec for `incomingPaymentCreated` event and `amount` schema in OpenAPI specs file, `webhooks.yaml`. This schema was already defined in the Open Payments resource server specs and copied using `postinstall` and `copy-op-schemas` scripts. These scripts were removed from `package.json` as they are no longer necessary.
This issue fixes #2920
=> docs: added spec for 'incomingPaymentCreated' and schema for 'amount' in webhooks.yaml

localenv/mock-account-servicing-entity/app/lib/apolloClient.ts, localenv/mock-account-servicing-entity/app/lib/requesters.ts, localenv/mock-account-servicing-entity/app/lib/webhooks.server.ts, packages/backend/src/tenant/service.ts, packages/mock-account-service-lib/src/account-provider.ts, packages/mock-account-service-lib/src/seed.ts
- Adds a `tenantId` instance variable to the `AccountProvider` class in the 	`mock-account-service-lib`.
Fixes #2992. 
If a mock ASE is queried for a wallet address that doesn't exist, it tries to create the wallet address. With the introduction of tenants, this breaks that request as it now expects a tenant id in the input. An instance variable allows the mock ase to configure the `AccountProvider` class with a tenant id with which to create wallet addresses.
=> feat(backend,localenv): add tenant id to mockAccounts class

packages/documentation/astro.config.mjs, packages/documentation/package.json, packages/documentation/src/styles/rafiki.css, pnpm-lock.yaml
- adds header links to docs headings. makes it easier to get link to specific sections by clicking on it (currently have to manually form the url). Style should be unchanged, other than underlining on hover.
https://github.com/user-attachments/assets/b9da2ebe-6065-486d-a65f-098a7599077d
I wanted to link to a specific section and found it annoying to do so without this.
=> feat(docs): add header links

packages/auth/src/app.ts, packages/auth/src/config/app.ts, packages/auth/src/tests/context.ts
Added a new ENV flag (INTERACTION_COOKIE_SAME_SITE) that is unset by default and allows the ASE to set it to lax, strict, or none if they want.
Added mainly for control over this value in auth.rafiki.money, in order to be able to have payments work in an iframe, needed in WM Tools
=> feat: Allow configurable cookie SameSite header

localenv/telemetry/otel-collector-config.yaml, packages/backend/src/app.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/lifecycle.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/payment-method/ilp/connector/core/rafiki.ts, packages/backend/src/payment-method/ilp/connector/index.ts, packages/backend/src/payment-method/ilp/service.ts, packages/backend/src/telemetry/service.test.ts, packages/backend/src/telemetry/service.ts
- makes the telemetry _service_ (not the actual collection) required and removes all the `if(telemetry)` checks
- changes otel collector log config to get rid of a lot of noise that was making logs unreadable
fixes #2980
=> refactor(backend): add NoopTelemetryServiceImpl to make tel optional

packages/documentation/src/content/docs/admin/admin-user-guide.mdx, packages/documentation/src/content/docs/integration/playground/overview.mdx, packages/documentation/src/content/docs/integration/services/frontend-service.mdx
Updated the following pages:
- Admin user guide - adding caution about disabling Kratos
- Frontend service - adding caution about disabling Kratos
- Local playground - adding information about Kratos being disabled by default and how to enable
Fixes https://github.com/interledger/rafiki/issues/2963
=> docs: rafiki admin auth optional

packages/auth/src/openapi/specs/id-provider.yaml
- Added missing response codes to id-provider specs
After reviewing all the OpenAPI specs, I have found two missing response statuses in the `id-provider.yaml`:
- `500` code at the request that starts the user interaction
- `404` code at the request that finishes the user interaction
Fixes #2958
=> docs: added missing responses to id-provider requests

packages/backend/src/config/app.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/open_payments/payment/outgoing/worker.ts
- Added a new ENV `MAX_OUTGOING_PAYMENT_RETRY_ATTEMPTS` for configuring the number of payment sending attempts, with a default value of `5`.
- Closes #3017
=> feat(backend): make payment retry attempts configurable via env

packages/auth/src/graphql/generated/graphql.schema.json, packages/auth/src/graphql/schema.graphql
Updated descriptions for the Auth Admin API. This fixes https://github.com/interledger/rafiki/issues/2987
While these changes are enhancements to the current reference docs, I understand that the graphql schemas are also used to generate other files/types.
=> docs: update graphql descriptions auth

packages/auth/src/graphql/schema.graphql, packages/backend/src/open_payments/payment/incoming/model.ts, packages/backend/src/open_payments/payment/incoming/service.test.ts, packages/backend/src/open_payments/payment/incoming/service.ts, packages/backend/src/payment-method/ilp/connector/core/middleware/account.ts
- Removing the 30 second wait time when completing or expiring an incoming payment. 
- The reason for the incoming payment would wait 30 seconds before "finalizing" it (via `processAt`), was to check for any packets that we're sent but not received, essentially, trying to make sure that we wouldn't "lose" any that should be delivered to the payment. However, in practice, it looks like this delay wouldn't have mattered/worked to begin with. Because we also update the status of the payment when changing `processAt`:
https://github.com/interledger/rafiki/blob/6b971bf4636bbc658530e8447c52866054db2aec/packages/backend/src/open_payments/payment/incoming/model.ts#L154-L164  _and_ we check for the incoming payment status when we received packets: …
=> chore(backend): dont wait 30s when completing/expiring incoming payment

packages/frontend/app/routes/auth._index.tsx
Using the `Form` with `redirectDocument(loginUrl);` By using remix's `action` function and `redirectDocument` instead of `href`, the server processes the request, retrieves the necessary information (such as flow parameters from Ory Kratos), and provides the correct redirect response. The form submit allows remix to handle this routing server-side, ensuring the full URL is correctly generated.
The `href` attribute instead tries to directly navigate to the link client-side. If variables.kratosBrowserPublicUrl is undefined or not available at runtime, Remix will interpret it as `undefined`, creating the `localhost:3010/undefined/self-service/login/browser` URL.
What were you trying to do?
fixes #2840
=> fix: Admin UI error Auth redirect

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/routes.ts
- Instead of returning 400 return 404 if token cannot be rotated
- fixes #3100
=> feat(auth): return GNAP 404 error if token cannot be rotated

packages/frontend/app/components/RedirectDialog.tsx, packages/frontend/app/lib/api/asset.server.ts, packages/frontend/app/routes/peers.create.tsx
- Fixed error when trying to create an peer with no existing assets.
- Added a dialog when opening the create peer page that can route the user to create asset page.
Fixes #3046 
When trying to create a peer with no existing assets, a 'cannot read properties of undefined' error occurred, because there was a mapper on the assets list. I fixed this by updating `loadAssets` to return `[]` in this case.
However, the user might start filling in the form and when he gets to the assets select field (which is the last one) there will be nothing. To prevent this, I added a dialog that warns the user that an asset should be created first and can go to create assets page.
=> fix: fixed error where no assets were found when opening create peer page

packages/backend/migrations/20241125224212_create_tenants_table.js, packages/backend/src/tenants/model.ts
- Add `tenants` table in migration for backend database
- Add ObjectionJS `model.ts` file to model tenants table schema
Closes #3103.
=> feat(backend): tenants table v1

packages/backend/src/payment-method/ilp/connector/core/middleware/expire.ts, packages/backend/src/payment-method/ilp/connector/core/test/middleware/expire-middleware.test.ts
- This PR updates error handling logic of packet expiry middleware so that node process does not crash/exit if a packet from the sending connector expires.
- fixes #3075
=> fix(backend): update packet expiry error handling

packages/backend/src/accounting/psql/ledger-transfer/index.test.ts, packages/backend/src/accounting/psql/ledger-transfer/index.ts, packages/backend/src/accounting/tigerbeetle/transfers.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/resolvers/accounting_transfer.psql.test.ts, packages/backend/src/graphql/resolvers/accounting_transfer.tigerbeetle.test.ts, packages/backend/src/graphql/schema.graphql
- Updated limit for `accountingTransfer` to 20
- Updated tests 
- Updated GraphQL description
Fixes #3003
=> chore: update accountingTransfer limit to 20

packages/auth/migrations/20241125233415_create_tenants_table.js, packages/auth/src/tenant/model.ts
- Add tenants table in migration for backend database
- Add ObjectionJS model.ts file to model tenants table schema
Closes #3113.
=> feat(auth): tenants table v1

packages/backend/src/open_payments/payment/outgoing/worker.ts
- Use asset and wallet address cache in outgoing payments worker
- Parent issue #2979, related to #2981, 2982
=> feat(backend): use cache when fetching outgoing payment in worker

packages/auth/migrations/20241125233415_create_tenants_table.js, packages/auth/src/app.ts, packages/auth/src/index.ts, packages/auth/src/tenant/service.test.ts, packages/auth/src/tenant/service.ts
-  Adds tenant service to `auth`
- Fixes https://github.com/interledger/rafiki/issues/3122
=> feat(auth): tenant service

.prettierignore, packages/documentation/astro.config.mjs, packages/documentation/src/content/docs/integration/playground/overview.mdx, packages/documentation/src/content/docs/integration/prod/docker-compose.mdx, packages/documentation/src/content/docs/integration/requirements/wallet-addresses.mdx, packages/documentation/src/content/docs/integration/requirements/webhook-events.mdx, packages/documentation/src/content/docs/overview/concepts/telemetry.mdx, packages/documentation/src/content/docs/resources/glossary.mdx, packages/documentation/src/partials/auth-variables.mdx, packages/documentation/src/partials/backend-variables.mdx, packages/documentation/src/partials/frontend-variables.mdx
- After researching Prettier and the formatting options it includes I believe it is useful for our docs with the current configuration settings. 
- Further investigation will need to be done on what's causing issues as they crop up again in the future for the docs writers. 
Fixes #2942
=> chore: re-enable Prettier for docs

packages/backend/src/telemetry/service.test.ts, packages/backend/src/telemetry/service.ts
- Fix incrementCounterWithTransactionAmount metric collection
Fixes #3145
=> chore(backend): fix incrementCounterWithTransactionAmount function

packages/backend/src/payment-method/local/service.test.ts, packages/backend/src/rates/util.test.ts, packages/backend/src/rates/util.ts
- updates rate calculation to not invert
fixes #3163
=> fix(backend): inverted rate

packages/frontend/app/shared/utils.ts
- Fix wallet address creation page by updating `getOpenPaymentsUrl` function to account for function running client-side
Fixes #3161
=> fix(frontend): wallet address creation page

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml, packages/backend/jest.config.js, packages/backend/migrations/20241125224212_create_tenants_table.js, packages/backend/package.json, packages/backend/src/config/app.ts, packages/backend/src/index.ts, packages/backend/src/tenants/model.ts, packages/backend/src/tenants/service.test.ts, packages/backend/src/tenants/service.ts, packages/backend/src/tests/tenant.ts, pnpm-lock.yaml, test/integration/testenv/cloud-nine-wallet/docker-compose.yml, test/integration/testenv/happy-life-bank/docker-compose.yml
- Adds a `TenantService` to the backend IoC container
- Adds `updatedAt` and `createdAt` in the backend tenants table.
Closes #3123.
=> feat(backend): tenants service (#3123)

packages/backend/src/app.ts, packages/backend/src/tests/app.ts, pnpm-lock.yaml, test/integration/lib/apollo-client.ts, test/integration/lib/config.ts, test/integration/lib/mock-ase.ts, test/integration/package.json, test/integration/testenv/cloud-nine-wallet/.env, test/integration/testenv/cloud-nine-wallet/docker-compose.yml, test/integration/testenv/happy-life-bank/.env, test/integration/testenv/happy-life-bank/docker-compose.yml
- Now that API_SECRET is required in `backend` (for seeding operator tenant in #3149), we need to have request signing for the Admin API in all places. This PR adds signature signing to the integration tests and ignores the signature signing during normal `backend` tests
Related to #3149
=> feat(integration): sign Admin API requests during integration tests

packages/documentation/astro.config.mjs, packages/documentation/src/content/docs/integration/requirements/overview.mdx
=> docs: mi/3170/overview updates

README.md, localenv/README.md, packages/documentation/src/content/docs/integration/playground/overview.mdx
This PR improves the Rafiki documentation by enhancing clarity, filling gaps in the setup process, linking related resources, and removing ambiguity and redundancy. Addresses issue https://github.com/interledger/rafiki/issues/3034
- Clarified the purpose of this package as part of the greater Rafiki context
- Updated steps for setting up the local playground
- Highlighted the distinction between Cloud Nine Wallet and Happy Life Bank
- Removed much of the in-depth content and provided direct links to the appropriate pages in the Rafiki docs
- Updated to match wording/structure when we did Local Playground doc revisions
- Fixed the time of the weekly community call
- Added more explicit instructions around cloning the repo and initial setup of the environment
- Improved the dependency setup …
=> docs: Improve local dev setup process through readme and doc edits

packages/backend/src/payment-method/ilp/connector/core/README.md, packages/documentation/src/content/docs/overview/concepts/telemetry.mdx
Change references to ILP packets (prepare, fulfill, reject) from lower to upper case. Typescript files are ignored.
=> docs: update telemetry.mdx and readme

packages/backend/src/graphql/resolvers/tenant.ts, packages/backend/src/tenants/service.test.ts, packages/backend/src/tenants/service.ts, packages/frontend/app/routes/tenants.$tenantId.tsx, packages/frontend/app/routes/tenants._index.tsx
- https://github.com/interledger/rafiki/issues/3256
Fixes #3256
=> feat(backend/frontend): 3256 able to view deleted tenant

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/asset.test.ts, packages/backend/src/graphql/resolvers/asset.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/tests/app.ts, packages/frontend/app/components/ui/Select.tsx, packages/frontend/app/generated/graphql.ts, packages/frontend/app/lib/api/asset.server.ts, packages/frontend/app/lib/api/tenant.server.ts, packages/frontend/app/lib/apollo.server.ts, packages/frontend/app/lib/validate.server.ts, packages/frontend/app/routes/assets.create.tsx, packages/frontend/app/routes/peers.create.tsx, packages/frontend/app/routes/wallet-addresses.create.tsx, packages/frontend/app/styles/tailwind.css, packages/mock-account-service-lib/src/generated/graphql.ts, test/integration/lib/generated/graphql.ts
- Adds tenant dropdown menus if the user is an operator for the following `frontend` pages:
- Asset creation
- Wallet Address creation
- Peer creation
- These resources will be created with the selected tenant, or with the selected asset associated with a given tenant.
- Does not display this option if the user is a tenant.
Fixes #3273.
=> feat(frontend): add operator-contextual dropdowns for tenant selection

packages/auth/Dockerfile.dev, packages/auth/Dockerfile.prod, packages/backend/Dockerfile.dev, packages/backend/Dockerfile.prod, packages/frontend/Dockerfile.dev, packages/frontend/Dockerfile.prod
- Modified both the dev and prod Dockerfiles of all the services to run as the non-root Rafiki user.
- To achieve this we have to chown the packages back to rafiki after each copy to ensure the ownership is correct. Otherwise the build process create the symlinks it wants to make.
As part of me trying to get into understanding the build pipeline, I noticed that the docker containers currently run as the root user which can be considered a security issue.
- For dev builds we have to switch between Rafiki and root user during the build process to ensure everything links correctly
- For prod builds, only the run-container will now run as Rafiki user, but with read-only access to the packages folder
Just to make it clear, after the change this is the status:
```sh
$ docker exec …
```
=> build: containers will now run as the non-root rafiki user

infrastructure/helm/tigerbeetle/values.yaml, localenv/tigerbeetle/docker-compose.yml, packages/backend/package.json, packages/backend/src/accounting/tigerbeetle/service.test.ts, packages/backend/src/accounting/tigerbeetle/transfers.ts, packages/backend/src/tests/tigerbeetle.ts, packages/documentation/src/content/docs/integration/deployment/docker-compose.mdx, pnpm-lock.yaml
- Please see: https://github.com/interledger/rafiki/issues/3322
=> feat(3322-tigerbeetle): bump tb from 0.15.4 to 0.16.29

packages/auth/package.json, packages/auth/src/app.ts, packages/auth/src/interaction/routes.test.ts, packages/auth/src/interaction/routes.ts, packages/auth/src/openapi/specs/id-provider.yaml, pnpm-lock.yaml
- Adds the `gnapServerErrorMiddleware` to the routes on the Identity Provider API on the auth server.
Closes #3029.
This ended up being a one-line change, as the IDP responses were added already in the spec from #850 and #3024. The code already throws these errors and had tests added as of #2400. There was one potential response missing from the spec, however.
=> feat(auth): use gnap error middleware on idp api

packages/auth/src/interaction/routes.test.ts, packages/auth/src/interaction/routes.ts
- Adds interaction expiry check to interaction finish endpoint, before the session check.
- Throws an error or redirects to client on interaction start and finish endpoints, depending on if the associated grant has a finish URI or not.
Fixes #3318.
=> feat(auth): handle expired interactions gracefully during finish

packages/backend/src/open_payments/payment/incoming/model.test.ts, packages/backend/src/open_payments/payment/incoming/model.ts, packages/backend/src/open_payments/payment/incoming/routes.ts, packages/backend/src/open_payments/payment/outgoing/lifecycle.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/open_payments/quote/service.ts, packages/backend/src/open_payments/receiver/model.test.ts, packages/backend/src/open_payments/receiver/model.ts, packages/backend/src/open_payments/receiver/service.test.ts, packages/backend/src/open_payments/receiver/service.ts, packages/backend/src/payment-method/ilp/stream-credentials/service.test.ts, packages/backend/src/payment-method/ilp/stream-credentials/service.ts, packages/backend/src/tests/quote.ts
- moved validation checks (completed, expired and methods availability) to createOutgoingPayment, handleSending, resolveReceiver via `Resolver.isInvalidExpiredOrCompleted`
fixes #3253
=> fix(backend): allow admin api to query all receivers and move checks

packages/documentation/astro.config.mjs
Changed Rafiki doc theme color from orange to teal. Closes doc-design-system issue 36.
=> docs: change theme to teal

packages/documentation/astro.config.mjs, packages/documentation/package.json, packages/documentation/src/components/Header.astro, packages/documentation/src/components/PageSidebar.astro, pnpm-lock.yaml
- Bumps all the docs dependencies to their latest versions
- Updates the astro.config.mjs to address the breaking change from https://github.com/withastro/starlight/blob/main/packages/starlight/CHANGELOG.md#0330
- Standard dependency update chore
=> chore: bump dependencies to latest versions

packages/documentation/src/content/docs/admin/liquidity/asset-liquidity.mdx, packages/documentation/src/content/docs/admin/liquidity/payment-liquidity.mdx, packages/documentation/src/content/docs/admin/liquidity/peer-liquidity.mdx, packages/documentation/src/content/docs/admin/liquidity/two-phase-transfers.mdx, packages/documentation/src/content/docs/integration/requirements/assets.mdx, packages/documentation/src/content/docs/integration/requirements/open-payments/grants-revoking.mdx, packages/documentation/src/content/docs/integration/requirements/open-payments/wallet-keys.mdx, packages/documentation/src/content/docs/integration/requirements/peers.mdx, packages/documentation/src/content/docs/integration/requirements/sending-fees.mdx, packages/documentation/src/content/docs/integration/requirements/wallet-addresses.mdx
Each GraphQL example is in a 3-tabbed panel: one for operation, one for arguments, and one for response.
Fixes https://github.com/interledger/rafiki/issues/3090
=> docs: standardize graphql examples

packages/documentation/src/content/docs/index.mdx
Updates to Rafiki landing screen: add links to local playground and integration requirements. Remove link for Github (it's still in the top nav).
=> docs: fixes #3380

packages/documentation/astro.config.mjs, packages/documentation/src/content/docs/integration/deployment/docker-compose.mdx, packages/documentation/src/content/docs/overview/overview.mdx
Addresses issue # 3381
1. Updated heading to "Peer-to-peer payments between ASEs"
2. Moved APIs above Resources in left TOC
3. Added note to Docker Compose page that while it could be used for production, it is ideally for development and testing.
=> docs: mi/3381/updates-feedback

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml
- Use `https` in the `OPEN_PAYMENTS_URL` backend environment variable for the local environment configuration.
Closes #3409.
After #3325 was merged in, the seeding for the local environment was broken since wallet addresses were being compared against the `OPEN_PAYMENTS_URL` - and the discrepancy in http protocol between the local environment config for `backend` and the submitted wallet addresses in the seed caused the wallet address creation to fail during seeding.
=> fix(localenv): use https in openPaymentsUrl vars in local backend config

packages/backend/src/open_payments/payment/outgoing/worker.ts, packages/backend/src/payment-method/local/service.test.ts, packages/backend/src/payment-method/local/service.ts, test/integration/integration.test.ts, test/integration/lib/test-actions/admin.ts, test/integration/lib/test-actions/index.ts, test/integration/lib/test-actions/open-payments.ts, test/test-lib/src/admin-client.ts, test/testenv/cloud-nine-wallet/seed.yml, test/testenv/happy-life-bank/seed.yml
[Slack thread](https://interledgerfoundation.slack.com/archives/C05EMHTG6FM/p1746616946149559)
- During local payments, we should allow paying multiple outgoing payments into a single incoming payment, just like ILP payments.
- Added integration test for this
Fixes #3427
=> fix(backend): local payments - allow multiple outgoing payments pay into single incoming 

localenv/telemetry/grafana/provisioning/dashboards/example.json, packages/backend/src/open_payments/payment/outgoing/lifecycle.ts
- Collects and publishes the telemetry on how long a Rafiki instance takes to complete processing an outgoing payment.
- Adds a graph in the local environment's Grafana dashboard to display the times spent processing an outgoing payment.
Closes #3397 / RAF-1048.
=> feat(localenv): add histogram for outgoing payment completion time

localenv/mock-account-servicing-entity/package.json, packages/auth/package.json, packages/backend/package.json, packages/documentation/package.json, packages/frontend/package.json, packages/mock-account-service-lib/package.json, pnpm-lock.yaml, test/test-lib/package.json
- upgrades `graphql` to latest
_Somewhat_ resolves the issues encounter here where upgrading `graphql` in `documentation` causes another service to fail https://github.com/interledger/rafiki/pull/3431.
This issue was `auth` failing to build when upgrading `graphql` to latest in `documentation`.
```
> [builder 5/5] RUN pnpm --filter auth build:
10.67   Type '{ plugins: (LoggingPlugin | ApolloServerPlugin<BaseContext>)[]; introspection: boolean; validationRules: ValidationRule[]; allowBatchedHttpRequests: false; includeStacktraceInErrorResponses: false; schema: GraphQLSchema; }' is not assignable to type 'ApolloServerOptionsWithSchema<BaseContext>'.
10.67     Types of property 'validationRules' are incompatible.
10.67       Type 'import("/home/rafiki/node_modules/.pnpm/graphql@16.11.0/node_m …
```
=> chore: upgrade graphql

packages/backend/src/graphql/resolvers/peer.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/payment-method/ilp/connector/core/middleware/account.ts, packages/backend/src/payment-method/ilp/connector/core/test/middleware/account-middleware.test.ts, packages/backend/src/payment-method/ilp/peer/service.ts
- Make tenantId required in `peerService.getByDestinationAddress`
Whenever we are lookup a peer by destination address (particularly during payment processing in the connector), a situation may arise where multiple tenants have the configured the same peer, with the same destination (ILP) address. In order to avoid confusion, `peerService.getByDestinationAddress` now requires `tenantId`. This ensures that whenever outgoing payments are made to a peer Rafiki across ILP, the peer must be for the same tenant as the outgoing payment.
Follow up to #3129
=> feat(backend): required tenantId when fetching peer by destination address

localenv/cloud-ten-wallet/seed.yml, localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/tenant.test.ts, packages/backend/src/graphql/resolvers/tenant.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/tenants/errors.ts, packages/backend/src/tenants/service.test.ts, packages/backend/src/tenants/service.ts, packages/backend/src/tenants/settings/service.test.ts, packages/backend/src/tests/tenant.ts, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, packages/mock-account-service-lib/src/requesters.ts, packages/mock-account-service-lib/src/seed.ts, packages/mock-account-service-lib/src/types.ts, test/test-lib/src/generated/graphql.ts
- Allows `id` to be specified during the `createTenant` mutation. If not provided, the id will be generated automatically.
- Adds a specified `id` to the tenant seed for the Tenanted Mock ASE.
Fixes #3456 or #RAF-1070.
=> feat(backend): allow tenant id to be specified during tenant creation

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/migrations/20250625121526_replace_combined_payments_view.js, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/combined_payments.ts, packages/backend/src/graphql/resolvers/webhooks.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/open_payments/payment/combined/model.ts, packages/backend/src/open_payments/payment/combined/service.test.ts, packages/backend/src/open_payments/payment/combined/service.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/tests/combinedPayment.ts, packages/backend/src/webhook/service.test.ts, packages/backend/src/webhook/service.ts, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, test/test-lib/src/generated/graphql.ts
After testing the multi-tenancy branch, I found three pagination resolvers that needed a tenantId:
- webhook pagination resolver
- outgoing payments pagination resolver
- combined payments pagination resolver
Fixes #3473
=> feat(backend): add tenantId to webhook, outgoing + combined payments pagination resolvers

localenv/cloud-nine-wallet/dbinit.sql, localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml, packages/point-of-sale/Dockerfile.dev, packages/point-of-sale/Dockerfile.prod, packages/point-of-sale/knexfile.js, packages/point-of-sale/package.json, packages/point-of-sale/src/app.ts, packages/point-of-sale/src/config/app.ts, packages/point-of-sale/src/index.ts, packages/point-of-sale/tsconfig.json, pnpm-lock.yaml
=> feat: initialize POS service

localenv/cloud-nine-wallet/dbinit.sql, localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml
- HLB card and POS services now wait for the ones from C9 in order to avoid collision when building the images
=> fix: docker compose fix (for slower PCs) on localenv

packages/documentation/src/components/Header.astro
- This PR fixes the header of the docs sites, where the home link now detects the current active locale, and shows the language selector on the landing page
=> fix: resolve i18n-related issues for docs header

packages/card-service/package.json, pnpm-lock.yaml
- This PR adds the following missing dependencies in the package.json file:
```
-    "@koa/router": "^12.0.2",
-     "koa-bodyparser": "^4.4.1",
-     "pg": "^8.11.3",
```
=> fix(cards-service): add dependencies to package.json

packages/card-service/jest.config.js, packages/card-service/jest.custom-environment.ts, packages/card-service/jest.env.js, packages/card-service/jest.setup.ts, packages/card-service/jest.teardown.js, packages/card-service/package.json, packages/card-service/scripts/init.sh, packages/card-service/src/tests/app.ts, packages/card-service/src/tests/tableManager.ts, pnpm-lock.yaml
- This PR makes use of the testcontainers package in order to create testing runtime docker containers.
It is using the same setup as the backend and auth packages
=> feat(card-service): introduce testcontainers for database and redis

packages/point-of-sale/src/app.ts, packages/point-of-sale/src/index.ts, packages/point-of-sale/src/merchant/devices/service.test.ts, packages/point-of-sale/src/merchant/devices/service.ts, packages/point-of-sale/src/merchant/routes.test.ts, packages/point-of-sale/src/merchant/routes.ts, packages/point-of-sale/src/merchant/service.test.ts, packages/point-of-sale/src/merchant/service.ts
- Introduces delete merchant route.
Deleting a merchant should perform a cascade revoke on all it's pos devices.
[Closes RAF-1121](https://linear.app/interledger/issue/RAF-1121/pos-service-delete-merchantsmerchantid-route)
=> feat(pos-service): delete merchant route

bruno/collections/Rafiki/POS Service APIs/Create Merchant.bru, bruno/collections/Rafiki/POS Service APIs/Register POS Device.bru, bruno/collections/Rafiki/POS Service APIs/folder.bru
- Adds Bruno calls to:
- Create a merchant (POST /merchants)
- Register a POS Device (POST /merchants/:merchantId/devices)
Fixes RAF-1118 and fixes RAF-1119.
=> feat: bruno calls for creating merchant and registering POS device

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/migrations/20250708070748_create_outgoing_payment_card_table.js, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/open_payments/payment/outgoing/card/model.ts, packages/backend/src/open_payments/payment/outgoing/errors.ts, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, test/test-lib/src/generated/graphql.ts
Update Outgoing Payment GraphQl request to take in the expiry and the signature of a card to be passed along to the webhook
In the POS - Card Service relationship the Card Service need to pass along the outgoing payment request toughener with the card details to the ASE
[raf-1095
](https://linear.app/interledger/issue/RAF-1095/card-service-createcardpaymentbackend-api)
=> feat(backend): Raul/raf 1095 augment outgoing payments for card

packages/backend/src/graphql/resolvers/asset.test.ts, packages/backend/src/graphql/resolvers/combined_payments.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/peer.test.ts, packages/backend/src/graphql/resolvers/wallet_address.test.ts, packages/backend/src/graphql/resolvers/webhooks.test.ts, packages/backend/src/tests/combinedPayment.ts, packages/backend/src/tests/peer.ts, packages/backend/src/tests/webhook.ts
- Adds tests for the resolvers of several resources on the Rafiki Backend that test the following:
- The ability for an operator to paginate across all tenants for a given resource
- That a tenant does not paginate across all tenants for a given resource
- The ability for an operator to filter pagination results by any tenant
- That a tenant cannot filter pagination results by another tenant id
Fixes RAF-1080. Fixes #3476.
=> feat(backend): tenant id filter tests for gql pagination

packages/backend/src/card/service.ts, packages/backend/src/config/app.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/wallet_address/model.ts, packages/backend/src/open_payments/wallet_address/routes.ts, packages/frontend/app/generated/graphql.ts, packages/point-of-sale/src/graphql/generated/graphql.ts
- `CARD_SERVICE_URL` is now optional
- `OpenPaymentsWalletAddress` does not return `cardServiceUrl` if it's not set
Fixes #3577 
Linear [#1113](https://linear.app/interledger/issue/RAF-1134/backend-make-card-service-url-env-optional)
=> fix(backend): made CARD_SERVICE_URL optional

bruno/collections/Rafiki/Sample Webhook Events/Outgoing Payment Completed.bru, bruno/collections/Rafiki/Sample Webhook Events/Outgoing Payment Created.bru, bruno/collections/Rafiki/Sample Webhook Events/Outgoing Payment Failed.bru, packages/backend/migrations/20250827153829_drop_peer_id_from_outgoing_payments.js, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/openapi/specs/webhooks.yaml
Changes proposed in this pull request
This PR removes peer id from outgoing payment as it is not used anywhere in the project
Closes #3584.
=> chore(backend): remove peer id from outgoing payment model

packages/backend/src/config/app.ts, packages/backend/src/open_payments/payment/incoming/service.test.ts, packages/backend/src/webhook/service.test.ts, packages/backend/src/webhook/service.ts
This PR adds `POS_WEBHOOK_SERVICE_URL` env var and uses it when creating webhooks for incoming payment completions that were for card payments.
Closes RAF-1145
=> feat(backend): add custom webhook URL for POS

bruno/collections/Rafiki/POS Service APIs/Initiate Payment.bru, localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/schema.graphql, packages/card-service/src/graphql/generated/graphql.ts, packages/card-service/src/openapi/specs/card-server.yaml, packages/card-service/src/payment/routes.test.ts, packages/card-service/src/payment/service.test.ts, packages/card-service/src/payment/service.ts, packages/card-service/src/payment/types.ts, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, packages/point-of-sale/src/card-service-client/client.test.ts, packages/point-of-sale/src/card-service-client/client.ts, packages/point-of-sale/src/graphql/generated/graphql.ts, packages/point-of-sale/src/payments/routes.ts, test/test-lib/src/generated/graphql.ts
- Matched `POST /payment` bodies for `point-of-sale` and `card-service` (removed unnecessary fields)
- Fixed some GraphQL calls
- Updated OpenAPI spec for 'card-service'
Fixes #3622 
Linear [#1153](https://linear.app/interledger/issue/RAF-1153/pos-servicecard-service-reconcile-request-bodies-for-post-payment)
=> fix: match payment bodies for pos and card service

bruno/collections/Rafiki/POS Service APIs/Initiate Payment.bru, localenv/happy-life-bank/docker-compose.yml, packages/card-service/src/openapi/specs/card-server.yaml, packages/card-service/src/payment/routes.test.ts, packages/card-service/src/payment/service.test.ts, packages/card-service/src/payment/service.ts, packages/card-service/src/payment/types.ts, packages/point-of-sale/src/card-service-client/client.test.ts, packages/point-of-sale/src/card-service-client/client.ts, packages/point-of-sale/src/index.ts, packages/point-of-sale/src/payments/routes.test.ts, packages/point-of-sale/src/payments/routes.ts
After discussions in `#kernel-implementation`, we have finalized the POS Service `/payment` request that the POS will call. 
- Updated POS Service `POST /payment` request body to be:
```json
{
"signature": "", // hex string (GEN AC result)
"payload": "", // hex string (GEN AC payload)
"amount": { "value:": "100", "assetScale": 2, "assetCode": "EUR"},
"senderWalletAddress": "https://example.com/alice",
"receiverWalletAddress": "https://example.com/bob",
"timestamp": 1758105181325
}
```
- as a result, the Card Service `POST /payment` request body was updated to:
```json
{   
"requestId": "",
"signature": "",
"payload": "",
"amount": { "value:": "100", "assetScale": 2, "assetCode": "EUR"},
"timestamp": 1758105181325 
"senderWalletAddress": "https://example.com/alice",
"incomingPaymentUrl": …
```
=> feat(card-service, pos-service): updating payment routes with new payload

packages/backend/src/graphql/resolvers/webhooks.test.ts, packages/backend/src/graphql/resolvers/webhooks.ts
- This PR fixes resolver filtering for `outgoing_payment.funded` and `outgoing_payment.cancelled` events
-
=> fix(backend):  fix webhook resolver filter for OP funded and cancelled events

localenv/cloud-nine-wallet/docker-compose.yml, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/card-service/src/app.ts, packages/point-of-sale/src/card-service-client/client.test.ts, packages/point-of-sale/src/card-service-client/client.ts, packages/point-of-sale/src/payments/routes.test.ts
- Fetch cardDetails during outgoing payment funded and cancelled events, so it gets stored in the webhook data to send
- Add `CARD_WEBHOOK_SERVICE_URL` to cloud nine backend docker compose file
- Handle card service payment request data properly in POS service
Related to #3654 | RAF-1168
=> fix: updates to make e2e payment flow work

localenv/cloud-nine-wallet/docker-compose.yml, localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/card-service/src/app.ts, packages/card-service/src/graphql/generated/graphql.ts, packages/card-service/src/openapi/specs/card-server.yaml, packages/card-service/src/payment/routes.test.ts, packages/card-service/src/payment/routes.ts, packages/card-service/src/payment/service.test.ts, packages/card-service/src/payment/service.ts, packages/card-service/src/payment/types.ts, packages/card-service/src/payment/wait-map.test.ts, packages/card-service/src/payment/wait-map.ts, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, packages/point-of-sale/src/card-service-client/client.test.ts, packages/point-of-sale/src/card-service-client/client.ts, packages/point-of-sale/src/graphql/generated/graphql.ts, packages/point-of-sale/src/payments/routes.test.ts, test/test-lib/src/generated/graphql.ts
This PR handles the `outgoing_payment.funded` and `outgoing_payment.cancelled` events that we are sending from the backend to the card service ([RAF-1156](https://linear.app/interledger/issue/RAF-1156/backend-add-additional-webhook-events-for-outgoing-payments))
Closes [RAF-1168](https://linear.app/interledger/issue/RAF-1168/card-service-handle-payment-cancelled-and-funded-events)
=> feat(card-service): handle payment cancelled & funded events
