packages/backend/migrations/20210615140530_add_account_id_to_users_table.js, packages/backend/migrations/20210615140737_create_accounts_table.js, packages/backend/src/account/model.ts, packages/backend/src/account/service.test.ts, packages/backend/src/account/service.ts, packages/backend/src/user/model.ts, packages/backend/src/user/service.ts
- Adds `accounts` table and service.
- Creates an account and links it to a user when the user is created.
=> feat(backend): accounts service

packages/backend/src/account/service.test.ts, packages/backend/src/account/service.ts, packages/backend/src/shared/baseService.ts, packages/backend/src/user/service.test.ts, packages/backend/src/user/service.ts
- Refactors the services to use an object parameter instead of a parameter list.
=> refactor(backend): service dependencies param list -> object

.github/workflows/codeql-analysis.yml
=> feat(ci): add codeql workflow

.github/workflows/codacy-analysis.yml
=> feat(ci): add codacy workflow

.github/contributing.md, .github/labeler.yml, .github/workflows/label.yml, README.md
- Implements PR auto labelling for new labels.
- Documents the new label scheme in the contributing docs.
=> refactor: change autolabeller to match new labels

packages/interledger/src/admin-api/generated/graphql.schema.json, packages/interledger/src/admin-api/generated/graphql.ts, packages/interledger/src/admin-api/schema.graphql
=> chore(interledger): update credit and debt mutation schema

packages/interledger/src/accounts/service.ts, packages/interledger/src/accounts/types/accountsService.ts, packages/interledger/src/admin-api/generated/graphql.schema.json, packages/interledger/src/admin-api/generated/graphql.ts, packages/interledger/src/admin-api/resolvers/ilpAccount.test.ts, packages/interledger/src/admin-api/resolvers/ilpAccount.ts
=> feat(interledger): add getIlpAccounts resolver with pagination 

packages/interledger/src/accounts/service.test.ts, packages/interledger/src/accounts/service.ts, packages/interledger/src/accounts/types/accountsService.ts, packages/interledger/src/accounts/types/withdrawal.ts, packages/interledger/src/admin-api/generated/graphql.schema.json, packages/interledger/src/admin-api/generated/graphql.ts, packages/interledger/src/admin-api/resolvers/credit.test.ts, packages/interledger/src/admin-api/resolvers/index.ts, packages/interledger/src/admin-api/resolvers/withdrawal.test.ts, packages/interledger/src/admin-api/resolvers/withdrawal.ts, packages/interledger/src/admin-api/schema.graphql
- make withdrawals two-phase
- add withdrawal graphql mutation resolvers:
- createWithdrawal
- finalizePendingWithdrawal
- rollbackPendingWithdrawal
fixes #86 
fixes #87 
fixes #88
=> feat(interledger): add withdrawal mutation resolvers

packages/interledger/migrations/20210422194130_assets_table.js, packages/interledger/migrations/20210422194131_create_ilp_accounts_table.js, packages/interledger/src/accounts/errors.ts, packages/interledger/src/accounts/models/asset.ts, packages/interledger/src/accounts/models/ilpAccount.ts, packages/interledger/src/accounts/models/index.ts, packages/interledger/src/accounts/service.test.ts, packages/interledger/src/accounts/service.ts, packages/interledger/src/accounts/types/accountsService.ts, packages/interledger/src/accounts/types/deposit.ts, packages/interledger/src/accounts/types/withdrawal.ts, packages/interledger/src/accounts/utils/balance-id.ts, packages/interledger/src/admin-api/generated/graphql.schema.json, packages/interledger/src/admin-api/generated/graphql.ts, packages/interledger/src/admin-api/resolvers/withdrawal.ts, packages/interledger/src/admin-api/schema.graphql, packages/interledger/src/config/index.ts
- store ILP account asset in separate postgres table with `smallserial` used in Tigerbeetle account 2 byte `unit` field.
- store liquidity/settlement ids in assets table
fixes #114
=> fix(interledger): store asset in Tigerbeetle account 

packages/interledger/src/accounts/service.test.ts, packages/interledger/src/accounts/service.ts
- support same asset code, different scale transfers
- support same asset, different amounts transfers
fixes #118 
fixes #119
=> fix(interledger): support more asset/amount transfer combinations

.yarnrc.yml, packages/backend/migrations/20210422194130_create_assets_table.js, packages/backend/migrations/20210615140737_create_accounts_table.js, packages/backend/migrations/20211022210203_create_invoices_table.js, packages/backend/src/account/errors.ts, packages/backend/src/account/model.ts, packages/backend/src/account/routes.test.ts, packages/backend/src/account/routes.ts, packages/backend/src/account/service.test.ts, packages/backend/src/account/service.ts, packages/backend/src/app.ts, packages/backend/src/asset/model.ts, packages/backend/src/asset/service.test.ts, packages/backend/src/asset/service.ts, packages/backend/src/config/app.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/index.ts, packages/backend/src/invoice/model.ts, packages/backend/src/invoice/routes.test.ts, packages/backend/src/invoice/routes.ts, packages/backend/src/invoice/service.test.ts, packages/backend/src/invoice/service.ts, packages/backend/src/spsp/routes.test.ts, packages/backend/src/spsp/routes.ts, packages/backend/src/tests/context.ts
- Add a 'receive limit' to invoices.
- Add a new TigerBeetle account to the invoice's account to track the limit. This will (atomically) prevent transfers which would overpay the invoice. The invoice's limit is tracked by a **debit** account. The asset's counter-balance account is a **credit** account.
- Receipts aren't supported when paying to the invoice.
- If an invoice receives no payment before its expiry, it is deleted (see https://github.com/interledger/rafiki/issues/123).
- `MAX_EXPIRY` is currently set to 24 hours, but I picked that more-or-less at random.
Implement Open Payments invoices.
- Fixes https://github.com/interledger/rafiki/issues/123
=> open payments invoices

packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/graphql/schema.graphql
- add peer liquidity mutation resolvers
- remove interledger account liquidity mutation resolvers
- fixes #173
=> feat(backend): add peer liquidity mutation resolvers

packages/backend/migrations/20211026122545_create_outgoing_payments_table.js, packages/backend/src/app.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/errors.ts, packages/backend/src/open_payments/payment/outgoing/lifecycle.ts, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/routes.test.ts, packages/backend/src/open_payments/payment/outgoing/routes.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts
- add Open Payments Outgoing Payment endpoints:
- https://docs.openpayments.guide/reference/create-outgoing-payment
- https://docs.openpayments.guide/reference/get-outgoing-payment
- https://docs.openpayments.guide/reference/update-outgoing-payment
- fixes #252
=> feat(backend): add Outgoing Payment endpoints

.github/ISSUE_TEMPLATE/config.yml, .github/contributing.md, LICENSE, README.md, package.json
- updated repo URL all over the repo
- added info for joining the panning call
=> feat(docs): add planning call details

docs/transaction-api.md, packages/backend/migrations/20211026122545_create_outgoing_payments_table.js, packages/backend/src/app.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.test.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/open_payments/payment/outgoing/errors.ts, packages/backend/src/open_payments/payment/outgoing/lifecycle.ts, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/routes.test.ts, packages/backend/src/open_payments/payment/outgoing/routes.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/open_payments/payment/outgoing/worker.ts
- Remove support for re-quoting an outgoing payment.
- Remove outgoing payment authorization. #305 and #253 will handle authorization, primarily before an outgoing payment is created.
- fixes #304 
- progress towards #305
=> chore(backend): remove outgoing payment authorization and re-quote

packages/backend/codegen.yml, packages/backend/src/app.ts, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/models/incoming_payment.ts, packages/backend/src/graphql/models/index.ts, packages/backend/src/graphql/resolvers/account.ts, packages/backend/src/graphql/resolvers/apiKey.ts, packages/backend/src/graphql/resolvers/asset.ts, packages/backend/src/graphql/resolvers/incoming_payment.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/backend/src/graphql/resolvers/peer.ts, packages/backend/src/graphql/resolvers/session.ts, packages/backend/src/open_payments/payment/incoming/model.ts, packages/backend/src/open_payments/payment/incoming/routes.test.ts, packages/backend/src/open_payments/payment/incoming/routes.ts, packages/backend/src/open_payments/payment/incoming/service.test.ts, packages/backend/src/open_payments/payment/incoming/service.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts
- Add `IncomingPayment` mapper to exclude `receivedAmount` from resolver type.
- Use default [`resolverTypeWrapperSignature`](https://www.graphql-code-generator.com/plugins/typescript-resolvers) of `Promise<T> | T` since `IncomingPaymentEdge`'s node became `ResolversTypes['IncomingPayment']`
- Do not fetch `account` with an incoming payment since the asset is now available via the fetched `asset`.
- https://github.com/interledger/rafiki/pull/288#issuecomment-1086371488
=> fix(backend): fix AppServices typos

packages/backend/src/app.ts, packages/backend/src/config/app.ts, packages/backend/src/open_payments/auth/grant.test.ts, packages/backend/src/open_payments/auth/grant.ts, packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/middleware.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/tests/app.ts
- add Open Payments auth middleware
- perform token introspection and initial grant check.
- progress towards #253 (TODO: check grant limits in payment services)
=> feat(backend): add Open Payments auth middleware

packages/backend/src/app.ts
Add the graphql middleware first so that `/graphql` is not routed to the `accounting` endpoints.
Previously, visiting `/graphql` would return an `Invalid account id` error. This was being routed to the accounting endpoints instead of graphql.
=> fix(backend): make graphql path reachable

packages/backend/README.md, packages/backend/src/config/app.ts, packages/backend/src/index.ts
Connect to redis using a tls connection.
Additional env variables have been added to enable tls and configure the paths to the required tls certificates and key.
https://github.com/luin/ioredis\#tls-options
=> chore(backend):  redis tls config

packages/backend/README.md, packages/backend/jest.setup.js, packages/backend/src/tests/tigerbeetle.ts
- update the TB version to the latest, which allows backend tests to run on MacOS with M1 chip (when updated the `$HOME/.docker/daemon.json` as described in the backend README)
- fixes #299
=> chore: update tigerbeetle version

docs/transaction-api.md, packages/backend/migrations/20220414142553_create_outgoing_payments_table.js, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/routes.test.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/payment/outgoing/service.ts, packages/backend/src/tests/outgoingPayment.ts
- Include outgoing peer id in outgoing payment webhook events
- fixes #347
=> chore(backend): add peer to outgoing payment webhook events

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/routes.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/accessToken/service.ts, packages/auth/src/app.ts
- Implement access token revocation feature
fixes #336
=> feat(auth): access token revocation

.github/workflows/docker.yml
This PR adds an openapi build to the main docker build.
=> fix: add openapi build to main docker build

.github/workflows/lint_test_build.yml, .yarnrc.yml, packages/backend/Dockerfile
Add xz utils to the backend container to fix docker build
=> Add xz utils to the backend container to fix docker build

infrastructure/terraform/modules/cluster/resources.tf, infrastructure/terraform/modules/cluster/variables.tf, infrastructure/terraform/rafiki-test/variables.tf
Small change to split out the k8s node pool into multiple AZs.
=> split k8s nodes across azs

packages/backend/jest.setup.js
=> fix(tests): add withPrivilegedMode for tigerbeetle containers in test

packages/rates/package.json, rafiki-docker-compose.yml, yarn.lock
=> remove tb-init container

packages/rates/Dockerfile, rafiki-docker-compose.yml
Fixes the Dockerfile for the rates service and adds the rates service to the docker-compose file.
-
=> feat: add rates to docker-compose

.husky/pre-commit
- Remove the pre commit diff since its not working correctly now and is preventing commits locally
=> fix: remove the precommit git diff hook

.prettierrc.yml, jest.config.base.js, package.json, packages/auth/src/access/model.ts, packages/auth/src/accessToken/model.ts, packages/auth/src/grant/model.ts, packages/auth/src/index.ts, packages/backend/jest.setup.js, packages/backend/src/connector/core/test/middleware/reduce-expiry.test.ts, packages/backend/src/httpToken/model.ts, pnpm-lock.yaml
* remove ts-jest
* add @swc/jest
* fix relative dir for auth migrations
* optimize test containers to start in parallel
* fix import cyclic issues with objection models
* prettier changes
=> chore(testing): test optimizations

packages/backend/package.json, pnpm-lock.yaml
=> chore(deps): update more deps

renovate.json
- Updates renovate so that a pr is made on success or failure of the ci
=> chore(deps): make prs on success or failure from renovate after ci runs

packages/rates/package.json, tsconfig.json
-  Change the build order in the `tsconfig.json` since its an array and the order of dependencies matters.
=> fix: correct tsc build order, add clean to rates

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml, packages/backend/src/app.ts, packages/backend/src/config/app.ts, packages/backend/src/graphql/resolvers/index.test.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/tests/app.ts, packages/backend/src/tests/quote.ts
- separates app boot and server initializations.
- separates admin api url and open payments url.
- new env variables in docker configs.
- fixes #441
=> refactor(backend): separate admin and open payments server

renovate.json
- Disable renovate for now to reduce github actions usage
=> chore(deps): disable renovate for now

README.md, infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml, infrastructure/local/peer-setup.md, package.json, packages/auth/knexfile.js, packages/auth/seeds/development/01_grants.js, packages/auth/seeds/development/02_accesses.js, packages/mock-account-provider/src/app.ts
=> Peering docs

packages/backend/package.json, packages/backend/src/graphql/resolvers/index.test.ts, pnpm-lock.yaml
- Remove `got` dependency and replace with `axios` since it was only used for one test
=> chore(deps): remove got dependency

packages/backend/src/app.ts
- A function for generating a koa server with predefined middleware.
related suggestion comment [link](https://github.com/interledger/rafiki/pull/462#discussion_r951609991)
=> refactor(backend): koa server create function

packages/auth/package.json, packages/backend/package.json, packages/mock-account-provider/package.json, pnpm-lock.yaml
=> chore(deps): upgrade testcontainers

.github/workflows/docker-auth.yml, .github/workflows/docker-backend.yml, .github/workflows/lint_test_build.yml
- Adds timeouts for the github actions jobs
- Needs to be on a per job basis bc thats all github supports right now: https://github.com/orgs/community/discussions/25472
=> chore: add timesouts for github actions workflows

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/routes.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/accessToken/service.ts, packages/auth/src/config/app.ts
- adds client id to token introspection response
- bumps the version of the auth spec to validate against
- fixes #505
=> feat(auth): add client id to introspection response

README.md
=> fix(docs): fix README.md typo

.github/workflows/codeql-analysis.yml
=> chore: upgrade codeql version

.github/workflows/rafiki/env-setup/action.yml
- Add frozen lockflie check to ensure the lockfile is up to date
=> chore: add frozen lockfile

packages/auth/src/index.ts, packages/backend/src/index.ts
add exponential retry for the migrations of
auth and backend
-
=> feat(migrate): exponentially retry

packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/clientKeys.test.ts, packages/backend/src/graphql/resolvers/clientKeys.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/schema.graphql
=> feat(backend): graphql get client

packages/backend/codegen.yml, packages/mock-account-provider/app/entry.server.tsx, packages/mock-account-provider/generated/graphql.ts, packages/mock-account-provider/package.json, packages/mock-account-provider/seed.example.yml, packages/mock-account-provider/src/apolloClient.ts, packages/mock-account-provider/src/parse_config.ts, packages/mock-account-provider/src/requesters.ts, packages/mock-account-provider/src/run_seed.ts, pnpm-lock.yaml
Add liquidity cleanup and response type
=> feat: cleanup add liquidity

packages/mock-account-provider/app/lib/accounts.server.ts
- Add in memory account creation, lookup and debit / credit functionality
fixes #489
=> feat(moc-account-provider): add in memory account ledgering

packages/auth/src/app.ts, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/routes.ts
- Adds/updates routing to reflect latest OpenAPI schema changes:
- `grant` routes
- `accept`
- `reject`
- `/` (get info)
- `interact` routes
- `finish`
- `/` (start)
- fixes #426 
- see also interledger/open-payments#149
=> feat(auth): add new APIs to router

infrastructure/local/build-override.yml, infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml, package.json, packages/auth/seeds/development/01_grants.js, packages/auth/seeds/development/02_accesses.js, packages/auth/seeds/development/03_access_tokens.js, packages/backend/src/open_payments/payment_pointer/routes.test.ts, packages/backend/src/open_payments/payment_pointer/routes.ts, packages/mock-account-provider/Dockerfile, packages/mock-account-provider/app/routes/keys.$keyId.ts
=> fix: update local docker compose

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml, infrastructure/local/seed.peer.yml, infrastructure/local/seed.primary.yml
Adds the seed files into the containers. A separate PR will add retries in the seeding process to make sure that they wait for the respective Rafikis to be healthy before running.
=> feat: wire seed files into docker composes

packages/mock-account-provider/app/entry.server.tsx
Add retry function so that the seed process is resilient to other container startup times
=> feat: retry seed process for container startup lag

packages/backend/src/connector/core/middleware/account.ts, packages/backend/src/connector/core/test/middleware/account-middleware.test.ts, packages/mock-account-provider/app/routes/prices.ts, packages/mock-account-provider/app/routes/quotes.ts, packages/mock-account-provider/app/routes/webhooks.ts
=> fix: quote flow for local docker compose

packages/mock-account-provider/README.md, packages/mock-account-provider/app/entry.server.tsx, packages/mock-account-provider/app/lib/accounts.server.ts, packages/mock-account-provider/app/lib/apolloClient.ts, packages/mock-account-provider/app/lib/parse_config.ts, packages/mock-account-provider/app/lib/requesters.ts, packages/mock-account-provider/app/lib/run_seed.ts, packages/mock-account-provider/package.json, pnpm-lock.yaml
- Run the seed function when the mock account provider remix starts up
`fixes #489`
=> feat(MAP): run seed on startup and populate in memory account values

docs/account-service-api.md, docs/interledger-payment-request.md
- Mark specific docs as outdated so people don't think they are up to date.
=> chore: let folks know that specific docs need to be updated

packages/mock-account-provider/app/lib/accounts.server.ts, packages/mock-account-provider/app/lib/requesters.ts, packages/mock-account-provider/app/lib/run_seed.ts
- when creating a payment pointer map the account back to it
=> feat(MAP): add created payment pointer id to the mock accounts

packages/mock-account-provider/app/lib/accounts.server.ts
Acount existence check got inverted somehow I think.
=> fix: account existence check

infrastructure/local/seed.peer.yml, infrastructure/local/seed.primary.yml, packages/mock-account-provider/app/lib/parse_config.ts, packages/mock-account-provider/app/lib/run_seed.ts
=> feat: display pointers in output

packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/accessToken/service.ts, packages/auth/src/client/service.test.ts, packages/auth/src/client/service.ts, packages/auth/src/grant/service.test.ts, packages/auth/src/signature/service.test.ts, packages/auth/src/signature/service.ts, packages/auth/src/tests/signature.ts, packages/backend/src/clientKeys/routes.test.ts, packages/backend/src/clientKeys/routes.ts, packages/backend/src/clientKeys/service.test.ts, packages/backend/src/clientKeys/service.ts, packages/backend/src/index.ts, packages/mock-account-provider/generated/graphql.ts
=> refactor(gnap): remove client details from jwk

infrastructure/local/docker-compose.yml, infrastructure/local/seed.peer.yml, infrastructure/local/seed.primary.yml, packages/mock-account-provider/app/entry.server.tsx, packages/mock-account-provider/app/lib/parse_config.ts, packages/mock-account-provider/app/routes/quotes.ts, packages/mock-account-provider/seed.example.yml
- Adjusts send/receive amount based on some configured rates.
- Configures seeding to include rates.
=> feat(mock-account-provider): add quotes endpoint

packages/backend/src/index.ts
add logging to which port the server is running on
-
=> feat(backend): logging

packages/mock-account-provider/app/lib/accounts.server.ts
=> fix(MAP): correct credit value sanity check

packages/backend/src/app.ts
- Add payment pointer query path to route after all others
- Do not require trailing slash on payment pointer path
=> fix(backend): add payment pointer route last

packages/auth/src/access/service.test.ts, packages/auth/src/access/types.ts, packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/app.ts, packages/auth/src/config/app.ts, packages/auth/src/grant/model.ts, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/routes.ts, packages/auth/src/grant/service.test.ts, packages/auth/src/grant/service.ts, packages/auth/src/signature/service.test.ts
- Implements the following endpoints: 
- `GET /grant/:id/:nonce`
- `POST /grant/:id/:nonce/accept`
-  `POST /grant/:id/:nonce/reject`
- Modifies the following endpoints and moves some of their logic into the previously listed ones:
-  `GET /interact/:id/:nonce`
-  `GET /interact/:id/:nonce/finish`
Closes #554.
=> feat(auth): auth server api for idp consent screen, update stuff to match openapi spec

packages/backend/src/clientKeys/service.test.ts, packages/backend/src/clientKeys/service.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/clientKeys.test.ts, packages/backend/src/graphql/resolvers/clientKeys.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/schema.graphql, packages/mock-account-provider/generated/graphql.ts
- add function to clientKeys service to allow revoking keys.
fixes #482
=> feat(backend): allow revoking client keys

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml, packages/auth/src/app.ts, packages/auth/src/config/app.ts
- https://github.com/interledger/rafiki/issues/576#issuecomment-1230590971
- related to #576
=> chore(auth): make introspection httpsig validation optional

packages/backend/src/config/app.ts, packages/backend/src/open_payments/quote/routes.test.ts, packages/backend/src/open_payments/quote/routes.ts
- remove list quotes endpoint
- fixes #582
=> chore(backend): remove list quotes endpoint

packages/backend/src/apiKey/service.ts, packages/backend/src/connector/core/lib/crypto.ts, packages/backend/src/open_payments/payment/incoming/model.ts, packages/backend/src/open_payments/payment/incoming/routes.test.ts, packages/backend/src/open_payments/payment/incoming/routes.ts, packages/backend/src/open_payments/payment/incoming/service.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/session/service.ts, packages/backend/src/shared/baseModel.ts
- add incoming payment `url` and `completed` getters
- use undefined in incoming payment toJSON
- setup for #581
=> chore(backend): clean up incoming payment JSON conversion

packages/backend/src/connector/core/middleware/account.ts, packages/backend/src/connector/core/test/middleware/account-middleware.test.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/payment_pointer.test.ts, packages/backend/src/open_payments/payment_pointer/service.test.ts, packages/backend/src/open_payments/payment_pointer/service.ts, packages/backend/src/tests/paymentPointer.ts
- Create tigerbeetle liquidity account only when packets are received for payment pointer (SPSP fallback)
- fixes #521
=> chore(backend): delay payment pointer tigerbeetle account creation

packages/auth/seeds/development/02_accesses.js
- include required outgoing payment access `identifier` in seed grant
- fixes #611
=> fix(auth): include required identifer in seed grant

infrastructure/local/peer-setup.md
- The graphql playground links need the graphql path before they open up the playground. Otherwise you get a 404 error.
=> docs: the graphql playground links need the graphql path

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml
- Define `INTROSPECTION_HTTPSIG` as string in docker compose yaml files
=> fix(localenv): fix INTROSPECTION_HTTPSIG boolean definition in yaml

infrastructure/local/seed.peer.yml
- fix peer backend seed hostname
=> fix(localenv): fix peer backend seed hostname

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml
- Builds auth and backend packages instead of using published images
- Both are still being debugged, so running an old-non functioning image defeats the purpose
=> chore: add build path for auth and backend to docker compose

.github/labeler.yml
- add map and localenv to labeler
=> chore(ci): add map and localenv to labeler

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml
- Do not override pinned configured OpenAPI spec versions in docker compose files:
https://github.com/interledger/rafiki/blob/e8feb070f06f48db93cda1f683114616b175089c/packages/auth/src/config/app.ts#L26-L29
https://github.com/interledger/rafiki/blob/e8feb070f06f48db93cda1f683114616b175089c/packages/backend/src/config/app.ts#L104-L111
- related to #611
=> fix(localenv): use pinned OpenAPI spec versions in configs

packages/auth/src/app.ts
- Clearer enumeration of all the routes that are being mounted to the app
The old pattern of iterating through a list of routes and mounting each item as a route was not great for readability, so they are individually mounted so the different paths and methods can be seen in the code.
=> feat(auth): refactor route mounting to be more easily readable

packages/backend/src/config/app.ts, packages/backend/src/open_payments/auth/grant.ts, packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/middleware.ts, packages/backend/src/open_payments/auth/service.ts
Fix clientId -> client_id in introspection response. Update OpenAPI spec for introspection response validation.
- commit grant reference insert before calling next
- fix clientId -> client_id in introspection response.
=> fix(backend): commit grant reference insert before calling next

infrastructure/local/seed.peer.yml, infrastructure/local/seed.primary.yml, packages/backend/src/open_payments/amount.ts, packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/open_payments/quote/service.ts, packages/mock-account-provider/app/routes/quotes.ts, packages/mock-account-provider/seed.example.yml, packages/openapi/src/index.ts, packages/openapi/src/middleware.test.ts
- validate account provider-adjusted quote amounts
- include uint64 format in response validator
- fixes #624 
- fixes #625 
- fixes #621
=> fix(backend): validate account provider-adjusted quote amounts

packages/mock-account-provider/app/routes/webhooks.ts
- Clean up mock account provider webhook event parsing and handling
- fixes #628
=> fix(map): clean up webhook parsing

packages/backend/src/open_payments/payment/outgoing/lifecycle.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts
- base amount to deliver calculation on quote instead of receiver's `incomingAmount`
- fixes #633
=> fix(backend): base amount to deliver calculation on quote

packages/auth/src/app.ts, packages/auth/src/index.ts, packages/auth/src/signature/middleware.test.ts, packages/auth/src/signature/middleware.ts, packages/auth/src/signature/service.test.ts, packages/auth/src/signature/service.ts, packages/auth/src/tests/app.ts, packages/auth/src/tests/context.ts, packages/auth/src/tests/signature.ts
- Breaks down the middleware for parsing httpsig headers into separate smaller ones for each route, using their particular methods for acquiring a key.
Fixes #641.
=> refactor(auth): refactor httpsig into more specialized per-route middlewares

packages/backend/src/index.ts, packages/backend/src/open_payments/client/service.test.ts, packages/backend/src/open_payments/client/service.ts
- don't resolve local receiver over http
- progress towards #583
(Open Payments client service won't worry about grants when resolving local receivers)
=> chore(backend): don't resolve local receiver over http

packages/auth/Dockerfile, packages/backend/Dockerfile
Use previous `node:16-slim` image (instead of the latest `16.18.0`), in order to (temporarily) maximize Docker build cache usage
- related to #673
=> chore(docker): pin base image to node 16.17.1

.github/contributing.md, README.md
- Update contribution guidelines to remove yarn, and add pnpm
=> chore(docs): update Contributor Guidelines for Hacktoberfest

packages/auth/package.json, packages/backend/jest.setup.js, packages/backend/package.json, packages/backend/src/tests/tigerbeetle.ts, pnpm-lock.yaml
See: 
* https://github.com/testcontainers/testcontainers-node/issues/398
* https://github.com/tigerbeetledb/tigerbeetle/issues/92
=> feat(tests): replace privileged mode with --cap-add IPC_LOCK for TB

packages/backend/src/open_payments/payment/incoming/routes.test.ts, packages/backend/src/open_payments/payment/incoming/routes.ts
=> fix(backend): don't assign undefined to ilpStreamConnection

packages/open-payments/src/client/ilp-stream-connection.ts, packages/open-payments/src/client/incoming-payment.test.ts, packages/open-payments/src/client/incoming-payment.ts, packages/open-payments/src/client/index.ts, packages/open-payments/src/client/payment-pointer.test.ts, packages/open-payments/src/client/payment-pointer.ts, packages/open-payments/src/client/requests.ts, packages/open-payments/src/types.ts
- support payment pointer query
- related to #583 
RS needs to query receiver (incoming payment) payment pointer in order to determine that AS at which to request a grant (to query the receiver incoming payment)
=> feat(open-payments): add payment pointer query

packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/service.ts, packages/backend/src/open_payments/client/service.ts, packages/open-payments/src/client/requests.ts, packages/openapi/src/index.ts
=> fix(openapi): guard response body type

packages/backend/src/open_payments/payment/outgoing/routes.test.ts, packages/backend/src/open_payments/quote/routes.test.ts, packages/backend/src/open_payments/quote/routes.ts
=> fix(backend): store grantId on create quote route

packages/mock-account-provider/app/routes/webhooks.ts
- fix crediting on MAP by typecasting all payment amount values to bigint
- fixes #700
=> fix(map): cast all amount values to bigint

.gitignore
=> chore: added tmp folder to the root .gitignore file

infrastructure/local/dbinit.sql, infrastructure/local/docker-compose.yml, packages/auth/docker-compose.yml, packages/auth/jest.setup.js, packages/backend/docker-compose.yml, packages/backend/jest.setup.js
- Changing each database owner to its corresponding user 
Fixes #682.
Since the upcoming new version of Postgres (v15), only the database owner will be granted full access to the `public` schema. Other users will need to get an explicit `GRANT` to be able to make changes to the schema.
=> fix: update localenv for the latest postgres version

packages/backend/src/connector/core/middleware/balance.ts, packages/backend/src/connector/core/test/middleware/balance-middleware.test.ts
- Do not create (pending) transfers when receiving unfulfillable destination ILP packets
- fixes #205 
- related to #698
I tested that the quote + outgoing payment flow in Postman can be run twice (2nd quote now succeeds and outgoing payment is created, but never funded due to insufficient balance at map).
Error handling should still be improved for when there's a legitimate insufficient balance error in the connector (which should now only happen with outgoing payments instead of quotes).
=> chore(backend): skip balance updates on incoming rate probe packets

infrastructure/local/docker-compose.yml, infrastructure/local/peer-docker-compose.yml
=> chore(localenv): enable BYPASS_SIGNATURE_VALIDATION

packages/auth/scripts/get-op-schema.sh
Fixes OpenAPI response validation error in Postman grant request:
```
body.access_token.access.0.actions.0 must be equal to one of the allowed values
```
=> chore(auth): update OpenAPI specs

packages/auth/src/signature/middleware.test.ts, packages/auth/src/signature/middleware.ts
=> fix(auth): add clientKeyId to context

packages/open-payments/src/client/incoming-payment.test.ts, packages/open-payments/src/client/index.ts, packages/open-payments/src/client/outgoing-payment.test.ts, packages/open-payments/src/client/outgoing-payment.ts, packages/open-payments/src/index.ts, packages/open-payments/src/test/helpers.ts, packages/open-payments/src/types.ts
- Method for getting outgoing payment 
- Work towards #663
=> feat(open-payments): get outgoing payment

.github/codeql/source.yml, .github/codeql/tests.yml, .github/workflows/codeql-analysis.yml
=> chore(ci): exclude CodeQL hardcoded-credentials check in tests

packages/openapi/src/index.ts, packages/openapi/src/middleware.ts, packages/openapi/tsconfig.json
- 
- progress towards #781 
- fixes #577
=> fix(openapi): resolve type errors

packages/auth/src/access/types.ts
- Adds some actions specified in the OpenAPI spec to the in-code enum in the AS.
Closes #615.
=> feat(auth): add read-all and list-all actions

packages/open-payments/src/client/grant.test.ts, packages/open-payments/src/client/grant.ts, packages/open-payments/src/index.ts, packages/open-payments/src/test/helpers.ts, packages/open-payments/src/types.ts
(open-payments): continue grant 
- 
- [(open-payments): continue grant #811](https://github.com/interledger/rafiki/issues/811)
-
=> feat(open payments): continue grant added

.github/workflows/docker-auth.yml, .github/workflows/docker-backend.yml, .github/workflows/lint_test_build.yml, .github/workflows/rafiki/env-setup/action.yml
- Update workflows to the new `GITHUB_STATE` and `GITHUB_OUTPUT` environment files
- https://github.com/interledger/rafiki/issues/825
=> chore(ci): fix CI warnings

packages/open-payments/src/client/index.ts, packages/open-payments/src/client/quote.test.ts, packages/open-payments/src/client/quote.ts, packages/open-payments/src/types.ts
- add get quote method
fixes #809
=> feat(open-payments): add get quote route

packages/backend/src/app.ts, packages/backend/src/open_payments/auth/grant.ts, packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/middleware.ts, packages/backend/src/open_payments/auth/service.test.ts, packages/backend/src/open_payments/payment_pointer/model.test.ts, packages/backend/src/tests/context.ts
- separate auth (including introspection) and httpsig backend middleware
- move introspection tests from auth middleware to auth service 
setup for:
- https://github.com/interledger/rafiki/issues/844
- #798 
- #737
=> chore(backend): clean up auth service + middleware

packages/open-payments/src/client/token.test.ts, packages/open-payments/src/client/token.ts
- (open-payments): Add revokeToken function
[Add revokeToken function as is in document.](https://github.com/interledger/rafiki/issues/814)
Fixed issue #814
=> feat(open-payments): add revoketoken function

packages/backend/migrations/20211026133430_create_peers_table.js, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/peer.test.ts, packages/backend/src/graphql/resolvers/peer.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/peer/model.ts, packages/backend/src/peer/service.test.ts, packages/backend/src/peer/service.ts, packages/mock-account-provider/app/lib/parse_config.ts, packages/mock-account-provider/app/lib/requesters.ts, packages/mock-account-provider/app/lib/run_seed.ts, packages/mock-account-provider/generated/graphql.ts
- adds a name field for the peer model
fixes #827
=> feat(backend): adds a name field for the peer model

packages/auth/src/access/service.test.ts, packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/accessToken/service.ts, packages/auth/src/grant/routes.test.ts, packages/auth/src/grant/service.test.ts, packages/auth/src/grant/service.ts, packages/auth/src/shared/utils.ts
- Refactors nonce generation into a single utilty function.
Fixes #887.
=> refactor(auth): factor out nonce generation

packages/auth/src/openapi/id-provider.yaml
=> fix(auth): require interact params in query

packages/backend/src/connector/core/controllers/stream.ts, packages/backend/src/connector/core/middleware/error-handler.ts, packages/backend/src/connector/core/rafiki.ts, packages/backend/src/connector/core/test/controllers/stream-controller.test.ts, packages/backend/src/connector/core/test/middleware/error-handler-middleware.test.ts
=> chore(backend): revert incrementing total received on connector error

packages/auth/src/grant/routes.test.ts
- restructures grant route tests
- adds api spec checks for interaction route responses
- fixes #841
=> test(auth): add api spec checks for interaction route responses

packages/backend/codegen.yml, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/asset.ts, packages/backend/src/graphql/resolvers/outgoing_payment.ts, packages/mock-account-provider/generated/graphql.ts
=> chore(backend): allow null in GraphQL response

packages/open-payments/package.json, packages/token-introspection/package.json, pnpm-lock.yaml
- This reverts commit 644cb64d7a3ee00af058c29b689970b8d977e877.
- https://github.com/interledger/rafiki/pull/996#issuecomment-1387494584
=> Revert "chore(deps): update dependency openapi-typescript to v6 (#996)"

packages/backend/jest.setup.js
- check if tigerbeetle container log preference is set in environment variables
fixes #963
=> test: read tigerbeetle container log flag from env var

packages/backend/src/app.ts, packages/backend/src/open_payments/auth/middleware.test.ts, packages/backend/src/open_payments/auth/middleware.ts, packages/token-introspection/src/client/index.test.ts, packages/token-introspection/src/client/index.ts
=> fix(backend): fix introspect call

packages/backend/src/open_payments/quote/service.test.ts, packages/backend/src/webhook/service.test.ts
- removes `scrope.isDone()` and replaces it with `scope.done()`
- fixes #656 
- closes #725
=> chore: remove last occurences of nock `scope.isDone()`

packages/backend/src/accounting/service.ts, packages/backend/src/accounting/transfers.ts
- 
- fixes #966 
- fixes #968 
- fixes #964
=> chore(backend): update createTransfer options

pnpm-lock.yaml
- 
It looks like merging these two without merging `main` into the second messed up `pnpm-lock.yaml`
1. https://github.com/interledger/rafiki/pull/1034
2. https://github.com/interledger/rafiki/pull/1014
https://github.com/interledger/rafiki/actions/runs/4022704355/jobs/6912722599
=> fix(deps): update pnpm-lock.yaml

packages/backend/src/app.ts, packages/backend/src/open_payments/connection/middleware.test.ts, packages/backend/src/open_payments/connection/middleware.ts, packages/backend/src/open_payments/connection/routes.test.ts, packages/backend/src/open_payments/connection/routes.ts, packages/backend/src/spsp/middleware.test.ts, packages/backend/src/spsp/middleware.ts, packages/backend/src/spsp/routes.test.ts, packages/backend/src/spsp/routes.ts, packages/openapi/src/middleware.ts
- allow SPSP queries to both payment pointers and Open Payments connections
- fixes #1030 
- fixes #439
=> fix(backend): support SPSP queries

packages/backend/src/spsp/middleware.test.ts, packages/open-payments/src/client/requests.test.ts, packages/open-payments/src/client/requests.ts
- Specify Accept header for `open-payments` client requests to avoid wildcard content type.
https://github.com/axios/axios/issues/2927#issuecomment-620654080
- fixes #1081
=> chore(open-payments): specify Accept header

packages/backend/jest.setup.ts
- adds health check and wait strategy (waiting for health check to complete) to postgres  testcontainer
- fixes #1099
=> chore: add wait strategy for postgres

docs/peering.md
=> docs: add peering documentation

docs/renovate.md
=> docs: renovate bot

docs/open-payments.md
=> docs: explain Rafiki vs Open Payments

infrastructure/local/peer-docker-compose.yml, infrastructure/local/seed.peer.yml, infrastructure/local/seed.primary.yml, packages/backend/src/open_payments/quote/service.ts, packages/mock-account-provider/app/lib/parse_config.ts, packages/mock-account-provider/app/routes/quotes.ts
- adds log to quote service
- fixes quote endpoint in docker compose
- allows MAP to quote in different asset scales, which is necessary to create quote with newly generated asset using admin api postman collection
- related to #516
=> feat(map): quoting in multiple asset scales

packages/http-signature-utils/postman-scripts/preRequestSignatures.js
- 
- fixes #1155 
- fixes #1153
=> fix(hsu): Postman signature scripts allow for empty body in POST request

packages/backend/src/graphql/resolvers/peer.test.ts, packages/backend/src/graphql/resolvers/peer.ts, packages/backend/src/peer/service.test.ts, packages/backend/src/peer/service.ts
- Implement `deletePeer` mutation
- fixes #1154
=> feat(backend): implement delete peer

packages/backend/src/graphql/resolvers/peer.test.ts, packages/backend/src/peer/errors.ts, packages/backend/src/peer/service.test.ts, packages/backend/src/peer/service.ts, packages/backend/src/shared/utils.test.ts, packages/backend/src/shared/utils.ts
- adds validation for the peer's outgoing HTTP endpoint
- fixes #958
=> feat(backend): add http endpoint validation for peers

.github/contributing.md, README.md
=> chore(docs): document graphql-codegen script

docs/open-payments.md, packages/auth/README.md, packages/open-payments/scripts/fetch-schemas.sh
=> chore(openapi): use tagged spec version v1.0

docs/tigerbeetle.md
=> docs: tigerbeetle and rafiki

infrastructure/local/tigerbeetle/docker-compose.yml
- fixes Tigerbeetle container not starting in localenv
=> fix(localenv): tigerbeetle entrypoint

packages/token-introspection/README.md
- 
- fixes https://github.com/interledger/rafiki/issues/1262
=> docs(token-introspection): add README.md

packages/backend/src/open_payments/payment/incoming/service.test.ts
=> test(backend): make disparate asset test(s) consistent

.github/workflows/docker.yml, packages/auth/Dockerfile, packages/backend/Dockerfile
fixes [#1263](https://github.com/interledger/rafiki/issues/1263)
Also uses base images specific to the architectures which seems to speed up the builds a lot
-
=> fix(dockerbuild): architectures

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/label.yml, .github/workflows/lint_test_build.yml, .github/workflows/validate-openapi.yml
=> chore: pin ubuntu version in GH actions

.github/release.yaml, package.json
- bump version to v1.1.0-alpha
- add release.yaml
=> chore: bump version to 1.1.0-alpha

.github/workflows/docker.yml, packages/backend/Dockerfile
Github Action builds docker images on linux/amd64 which don't run on M1 machines. This PR forces backend docker image builds to happen on linux/arm64.
=> chore(backend): set build platform to linux/arm64

package.json
=> chore: bump version to 1.1.1-alpha

.github/workflows/pr_title_check.yml
- checks for conventional PR titles
- fixes #1342
=> chore: check for conventional commit msg PR titles

.github/workflows/docker.yml
=> fix: run docker build only on PRs and build+publish only on main+tags

.github/release.yaml, package.json, renovate.json
- set package version to 1.0.0
- will re-tag after this is merged (v1.0.0-alpha.1 instead of v1.1.0-alpha) and delete wrong tags and releases
- updated renovate config and release.yaml for better release notes
=> chore: fix releases

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/incoming_payment.test.ts, packages/backend/src/graphql/resolvers/incoming_payment.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/schema.graphql, packages/frontend/app/generated/graphql.ts
- adds `incomingPayment` resolver and unit test
- also added Get Incoming Payment request to Postman's `Rafiki Admin APIs`: https://www.postman.com/interledger/workspace/interledger/request/22855701-28f21533-1808-483e-ba36-4bd11ddba644
fixes #1343
=> feat: incoming payment resolver

packages/frontend/app/components/ConfirmationDialog.tsx, packages/frontend/app/components/Sidebar.tsx, packages/frontend/app/components/icons.tsx, packages/frontend/app/components/ui/Button.tsx, packages/frontend/app/routes/peers.$peerId.tsx
When dealing with irreversible actions, we only had a danger zone without any confirmation. This meant that if a user accidentally clicked on a delete button (e.g., delete peer button), the record would be immediately deleted. In this pull request, a confirmation dialog is introduced, along with a prompt that the user must complete before proceeding with irreversible actions.
<details>
<summary>Confirmation dialog preview:</summary>
https://github.com/interledger/rafiki/assets/60383558/8aa672f1-b375-4999-a39f-4dc946a4bff9
</details>
- closes #1446
=> feat(frontend): add confirmation dialog

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml
- Removing image from localenv docker compose files
Basically, the remote 'latest tagged' image will always be behind the local files on main that we use for the localenv. This means that if we have breaking changes that haven't been tagged as the 'latest' image, we will end up breaking localenv such as what happens currently on `main` in the mock account servicing entity:
```
2023-05-12 11:12:27 calling run_seed
2023-05-12 11:12:31 calling run_seed
2023-05-12 11:12:31 seeding failed with Error: Data was empty. If seeding has already completed this can probably be ignored
2023-05-12 11:12:25 [
2023-05-12 11:12:25   {
2023-05-12 11:12:25     message: 'Variable "$input" got invalid value { peerId: "b035f837-cb88-463d-9a87-858154b99237", amount: "100000", id: …
```
=> chore: remove remote image in docker compose files

.github/workflows/lint_test_build.yml, packages/backend/package.json
- to fix backend test timeout issues
- fixes #1470
=> chore: set dedicated num of workers for backend tests in CI

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/index.ts, packages/backend/src/graphql/resolvers/payment_pointer.test.ts, packages/backend/src/graphql/resolvers/payment_pointer.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/open_payments/payment_pointer/service.test.ts, packages/backend/src/open_payments/payment_pointer/service.ts, packages/backend/src/shared/pagination.test.ts, packages/frontend/app/generated/graphql.ts, pnpm-lock.yaml
- adds possibility to get page of payment pointers via Admin API
- fixes #1344
=> feat(backend): get page of payment pointers

packages/auth/src/grant/service.test.ts, packages/auth/src/grant/service.ts, packages/auth/src/graphql/generated/graphql.schema.json, packages/auth/src/graphql/generated/graphql.ts, packages/auth/src/graphql/resolvers/grant.test.ts, packages/auth/src/graphql/resolvers/grant.ts, packages/auth/src/graphql/resolvers/index.ts, packages/auth/src/graphql/resolvers/page.test.ts, packages/auth/src/graphql/scalars/BigInt.test.ts, packages/auth/src/graphql/scalars/BigInt.ts, packages/auth/src/graphql/scalars/UInt8.test.ts, packages/auth/src/graphql/scalars/UInt8.ts, packages/auth/src/graphql/scalars/index.ts, packages/auth/src/graphql/schema.graphql, packages/auth/src/shared/filters.ts, packages/auth/src/tests/grant.ts
- Add filter of grants by identifier defined in grant access. (As identifier does not exist on grant itself in db)
- Add graphql query to get grant by id
fixes #1505
=> feat(grant): add filter by identifier

packages/auth/package.json, packages/backend/package.json, pnpm-lock.yaml
- updates open-payments package to latest
Fixes #1437
=> fix(deps): update dependency open-payments to 2.0.0

infrastructure/helm/rafiki/README.md
=> fix: update example helm chart docs

packages/token-introspection/src/openapi/generated/types.ts, packages/token-introspection/src/openapi/token-introspection.yaml
- newer version of `openapi-typescript` discovered some ambiguity in our OpenAPI spec
- this PR 
- fixes ambiguity
- includes newly generated types
- fixes #1679
=> fix: token-introspection generate:types

packages/documentation/src/components/docs/LargeImg/LargeImg.module.css, packages/documentation/src/content/docs/concepts/asset.md, packages/documentation/src/content/docs/index.mdx, packages/documentation/src/content/docs/integration/event-handlers.md, packages/documentation/src/content/docs/integration/getting-started.md, packages/documentation/src/content/docs/integration/management.md, packages/documentation/src/content/docs/introduction/architecture.md, packages/documentation/src/content/docs/introduction/overview.md, packages/documentation/src/content/docs/playground/overview.md, packages/documentation/src/styles/ilf-docs.css
Closes #1778
This PR fixes:
1. the issue of side navigation not scrolling until the end of the main content by providing a height to the navigation container
2. the broken links to the glossary by updating the links to point to the correct URL
3. the focus of the CTA on the main landing page by directing folks to the docs and moving the Github link to the cards instead
=> fix: resolve issues raised in #1778

openapi/auth-server.yaml, packages/auth/src/access/service.test.ts, packages/auth/src/access/types.ts, packages/auth/src/accessToken/routes.test.ts, packages/auth/src/accessToken/service.test.ts, packages/auth/src/graphql/generated/graphql.schema.json, packages/auth/src/graphql/generated/graphql.ts, packages/auth/src/graphql/schema.graphql, packages/auth/src/signature/middleware.test.ts, packages/documentation/src/schema-dumps/auth_raw_schema.md, packages/token-introspection/src/openapi/token-introspection.yaml, postman/collections/Interledger.json
- Change references to `sendAmount` to `debitAmount`
Fixes #1769
=> feat(auth): change sendAmount to debitAmount

packages/auth/src/grant/model.ts
Correct endpoint:
- closes #1867
=> fix(auth): update continue uri

packages/documentation/package.json, pnpm-lock.yaml
=> chore(docs): bump astro-graphql-plugin to remove astro peer dependency

packages/documentation/package.json, packages/documentation/src/env.d.ts, packages/documentation/src/overrides/Header.astro, packages/documentation/src/styles/ilf-docs.css, pnpm-lock.yaml
- Bumps Starlight to latest
- Bumps Astro to latest
- Updates styling to match all other Starlight docs sites
Closes #1889
=> chore: update Starlight (and Astro) version

packages/backend/src/fee/model.test.ts
We overlooked a debug console.log in the tests. This removes it.
=> chore: remove debug console.log

.github/release.yaml
I added the "breaking" label to the breaking PRs and changed the GH workflow to put these into a separate section in the release notes.
=> chore: add "breaking changes" section to release notes

.github/contributing.md
Added `Reporting issues`, `Submitting Pull Requests` and `Review Process` sections to contributing.md
- 
These additional sections will guide the new contributors from picking up the issue to successfully submitting their PR.
=> chore: Added Few more sections to contributing.md

.github/workflows/postman-publish-main.yml, .github/workflows/postman-publish-tag.yml, .github/workflows/postman-publish.yml
- Checkout man branch when publishing postman API, to make sure that we can properly publish the API when creating a new release (a new tag). Tags are not recognized by the Postman Git integration
Fixes #1949
=> ci: checkout main branch when publishing postman API

packages/documentation/astro.config.mjs, packages/documentation/package.json, packages/documentation/src/content/docs/concepts/asset.md, pnpm-lock.yaml
- This PR updates use of our shared docs design npm package to the latest version which handles the breaking change introduced by the latest version bump of the mathjax plugin.
- Just double check that the MathJax renders as expected here: https://deploy-preview-1984--brilliant-pasca-3e80ec.netlify.app/concepts/asset/
Closes #1983
=> chore: dependency bumps

README.md
=> docs: resolve issues raised in #2001

packages/documentation/src/content/docs/integration/getting-started.md
Updated and fixed issue #1977 
Edited Docs and fixed minor changes.
More edits on the content for the docs are welcome.
=> docs: Updated Quotes/Rates #1977

scripts/fetch-schemas.sh
- Point to latest version of Open Payments in `fetch-schemas.sh`.
I updated the `fetch-schemas.sh` script to point to the v5.0.0 tag of Open Payments once released.
Closes #1979 .
=> chore: update `fetch-schemas.sh` to latest OP spec

README.md
- I have updated README.md to correct some spelling errors and grammatically incorrect sentences.
What were you trying to do?
Corrected grammatical errors and spelling errors to improve professionalism.
=> docs: Updated README.md to fix spelling and grammatical errors.

openapi/auth-server.yaml, packages/auth/src/interaction/routes.test.ts, packages/auth/src/interaction/routes.ts, packages/auth/src/openapi/id-provider.yaml
- returns interaction state in `/grant/:id/:nonce` lookup
fixes #1894
=> feat: returns interaction state in IDP grant lookup

localenv/mock-account-servicing-entity/app/lib/webhooks.server.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/open_payments/payment/incoming/model.ts, packages/backend/src/open_payments/payment/outgoing/model.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts
- Fix `IncomingPaymentEvent` and `PaymentEvent` to match `incomingPaymentEvent` schema in OpenAPI specification (https://github.com/daniel-shuy/rafiki/blob/1a0468d52b743f46d756ace804b723657bb5b6ee/packages/backend/src/openapi/webhooks.yaml#L113)
- Fix `PaymentEvent` to match `outgoingPaymentEvent` schema in OpenAPI specification (804b723657bb5b6ee/packages/backend/src/openapi/webhooks.yaml#L164)
fixes #1715
=> fix: WebhookEvent models to match OpenAPI specification

packages/backend/src/open_payments/payment_pointer/model.ts, packages/backend/src/openapi/webhooks.yaml, packages/documentation/src/content/docs/integration/event-handlers.md
- Update `PaymentPointerData` liquidity with `AmountJSON`
fixes #1650 
> * [x]  update the `PaymentPointerData` to remove `received: string` and add `receivedAmount: AmountJSON`
> * [x]  update the webhook open api spec
> * [ ]  make changes in mock ASE
> * [ ]  update the docs
=> refactor: Update Payment Pointer web monetization webhook 

packages/documentation/src/content/docs/concepts/interledger-protocol/overview.md, packages/documentation/src/content/docs/introduction/overview.md, packages/documentation/src/content/docs/reference/glossary.md
- Fixes to broken links in Glossary, Overview, and Interledger Protocol Overview doc pages
=> docs: fixed broken links in docs

packages/frontend/app/routes/_index.tsx
- Provides a basic home page for the Rafiki Admin UI
=> feat: created home page for Rafiki Admin

postman/collections/Interledger.json
- removes an extra 'f' char in our collection json file which was breaking postman
=> fix(postman): invalid json

postman/collections/Interledger.json
- fixes some examples > Open Payments requests. should now work up through incoming payment creation. quote create fails due to rafiki bug. this is necessary to reproduce https://github.com/interledger/rafiki/issues/2100
- updates usage of environment vars several places
progress towards https://github.com/interledger/rafiki/issues/2074
=> fix(postman): env var usage

packages/frontend/app/routes/assets.$assetId.tsx
- Made basis point fee explanation on Admin UI adapt to user input
- fixes #2089 
Input = 200
input = 3
No input
=> feat: basis point fee explanation

postman/collections/Interledger.json
- Disable Host header in complete incoming payments request
- Remove body from complete incoming payments request.
Fixes #2118.
Removes a couple of deprecated items that were malforming the complete incoming payment request.
=> fix(postman): complete incoming payment

localenv/mock-account-servicing-entity/app/lib/webhooks.server.ts
=> fix(mase): wallet address on the fly creation

scripts/localenv-tunnel-setup.js
- Rename payment pointer to wallet address in autopeering env variables
=> fix(autopeering): rename payment pointer env to wallet address

README.md
- updates readme to use correct command for verifying formatting
=> fix: readme cmd

packages/documentation/package.json, packages/documentation/src/styles/rafiki.css, pnpm-lock.yaml
- This PR updates Astro to the latest version
=> chore: docs dependency updates

packages/documentation/README.md, packages/documentation/src/content/docs/concepts/accounting/accounts-and-transfers.md, packages/documentation/src/content/docs/concepts/accounting/liquidity.md, packages/documentation/src/content/docs/concepts/interledger-protocol/peering.md, packages/documentation/src/content/docs/concepts/open-payments/overview.md, packages/documentation/src/content/docs/playground/overview.md
- Fixes two broken links and some grammar issues in docs
=> docs: fix broken links and grammar issues

packages/frontend/app/lib/validate.server.ts
Allow asset code length to be a maximum of 6 characters.
- 
Fixes #2139
=> feat: increase asset code length to 6 chars

packages/documentation/astro.config.mjs, packages/documentation/src/content/docs/integration/getting-started.md, packages/documentation/src/content/docs/playground/autopeering.md, packages/documentation/src/content/docs/playground/overview.md
- update local playground docs including
- referencing postman environments
- moving autopeering to own page
- update integration docs re: fees
- add link to OpenAPI specs for webhooks and rates endpoint to integration docs
=> docs: update

packages/documentation/astro.config.mjs, packages/documentation/package.json, packages/documentation/src/content/docs/concepts/interledger-protocol/peering.md, packages/documentation/src/content/docs/concepts/open-payments/key-registry.md, packages/documentation/src/content/docs/integration/event-handlers.mdx, packages/documentation/src/content/docs/integration/getting-started.md, pnpm-lock.yaml
- This PR updates our Mermaid implementation
- See https://github.com/interledger/docs-styleguide/issues/22 for backstory.
Closes #2235
=> refactor: update mermaid implementation

packages/documentation/README.md
- This PR updates the README within the documentation package to remove references to installing Playwright since we no longer use that
See https://github.com/interledger/docs-styleguide/issues/22 for more context
=> chore: update docs readme to remove playwright reference

packages/auth/src/accessToken/routes.ts, packages/auth/src/graphql/resolvers/grant.ts, packages/auth/src/index.ts, packages/backend/src/graphql/resolvers/asset.ts, packages/backend/src/graphql/resolvers/auto-peering.ts, packages/backend/src/graphql/resolvers/fee.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/graphql/resolvers/peer.ts, packages/backend/src/graphql/resolvers/receiver.ts, packages/backend/src/graphql/resolvers/walletAddressKey.ts, packages/backend/src/graphql/resolvers/wallet_address.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/incoming_remote/service.ts, packages/backend/src/open_payments/receiver/service.ts, packages/backend/src/open_payments/wallet_address/key/service.ts, packages/backend/src/payment-method/ilp/auto-peering/service.ts, packages/backend/src/payment-method/ilp/peer/service.ts, packages/backend/src/payment-method/ilp/service.ts
- fix pino error logging
- fixes #2210
=> fix: error logging

postman/collections/Interledger.json
- reverts a couple internal postman values that got improperly set
fixes: https://github.com/interledger/rafiki/pull/2151#pullrequestreview-1767986951
more context:
> Its something that Radu's PR did, since he cant access the postman workspace directly (and use Postmans git integration), so when he had to manually upload the collection it ended up putting an ID that didn't correspond to the existing collection so the github action to publish the API failed
=> fix(postman): broken publish

localenv/README.md
- I noticed some of the README links were outdated so I fixed them.
=> fix: updated asset links in localenv readme

packages/auth/src/grant/service.test.ts, packages/auth/src/grant/service.ts, packages/auth/src/graphql/generated/graphql.schema.json, packages/auth/src/graphql/generated/graphql.ts, packages/auth/src/graphql/resolvers/grant.test.ts, packages/auth/src/graphql/resolvers/grant.ts, packages/auth/src/graphql/resolvers/page.test.ts, packages/auth/src/graphql/schema.graphql, packages/auth/src/shared/baseModel.test.ts, packages/auth/src/shared/baseModel.ts, packages/auth/src/shared/pagination.ts
- Add sort order for grants graphql query
fixes #2305
=> feat(grants): add sorting option

postman/collections/Interledger.json
- Reverting postman/collections/Interledger.json file to alpha5 version and re-adds all of the newest changes since then to properly making publishing Postman APIs work (tested publishing manually and via the CLI)
Ever since [commit](https://github.com/interledger/rafiki/commit/2023d293e3ee5c5945b8fa374cbaaf6526d0b64d), the Postman API publish to `main` has not been working, since in the PR, the collection file, Interledger.json was exported and updated manually instead of via the Postman Git integration. It looks like each request needs an `id` to properly publish the API. This PR takes the collection from the working API collection of the alpha 5 tag, ands adds the changes since the alpha 5 release to make Postman API publishing work again.
Fixes #1949 
Also opened up an issue on the …
=> chore: fixing postman API publishing

packages/auth/src/graphql/resolvers/page.test.ts, packages/auth/src/index.ts, packages/backend/src/app.ts, packages/backend/src/graphql/resolvers/page.test.ts, packages/backend/src/open_payments/auth/middleware.ts, packages/backend/src/payment-method/ilp/connector/core/utils/create-context.ts, packages/backend/src/payment-method/ilp/connector/core/utils/http-mocks.ts, packages/backend/src/payment-method/ilp/spsp/middleware.test.ts, packages/backend/src/payment-method/ilp/spsp/middleware.ts
- removes uses of `ts-ignore` in favor of type assertions or fixing underlying types
These changes fall under a few categories:
- there was no ts error (code or tsconfig probably changed after comment was committed?) so I just removed the `ts-ignore` comment
- (most common) could not make it typesafe in which case I used type assertions instead of the `ts-ignore` comment. This is only a marginal improvement but I preferred this because it narrows the errors typescript will ignore and codifies the assumptions we are making.  For example, one of our `ts-ignore` comments was unintentionally hiding a `ReferenceError`: https://github.com/interledger/rafiki/pull/2340/commits/e6a643f294b71c57f5d622e0a0ce4e0aeb9e5f7e#r1450753470
- fixed the underlying typescript errors 🥳 
If I couldn't find a …
=> fix: improve type safety

infrastructure/helm/tigerbeetle/values.yaml, localenv/tigerbeetle/docker-compose.yml, packages/backend/package.json, packages/backend/src/accounting/psql/service.test.ts, packages/backend/src/accounting/psql/service.ts, packages/backend/src/accounting/service.ts, packages/backend/src/accounting/tigerbeetle/accounts.ts, packages/backend/src/accounting/tigerbeetle/errors.ts, packages/backend/src/accounting/tigerbeetle/service.test.ts, packages/backend/src/accounting/tigerbeetle/transfers.ts, packages/backend/src/graphql/resolvers/liquidity.test.ts, packages/backend/src/graphql/resolvers/liquidity.ts, packages/backend/src/index.ts, packages/backend/src/open_payments/payment/outgoing/service.test.ts, packages/backend/src/payment-method/ilp/connector/core/middleware/balance.ts, packages/backend/src/payment-method/ilp/connector/core/rafiki.ts, packages/backend/src/payment-method/ilp/connector/core/test/mocks/accounting-service.ts, packages/backend/src/tests/tigerbeetle.ts, pnpm-lock.yaml
- upgrade to newest tigerbeetle version such that the changes aren't big as soon as we get the TB production release
- progress towards #1438
- fixes #1112
=> chore: upgrade to newest tigerbeetle version

packages/backend/src/shared/utils.ts
I ran jest tests with `--detectOpenHandles` and found that the utils function for wallet address polling was causing an issue. This PR fixes that. However, it still does not fix the warning that I see when running backend tests 
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```
=> fix: jest open handles

bruno/collections/Interledger/environments/Local Playground.bru, bruno/collections/Interledger/environments/Remote.bru
- no copy-pasting from old sources
progress towards #2458
=> fix: make bruno client keys non-secret

localenv/README.md, packages/documentation/src/content/docs/playground/overview.md
Links to bruno collection were missing the `/tree/` in the path. This is a fix.
=> docs: fix broken bruno links

packages/backend/migrations/20231121184537_add_resource_fkeys_webhook_event.js
- Fixing webhookEvents migration to delete FK references to non-existing rows to prevent migration from failing
[Slack message](https://interledgerfoundation.slack.com/archives/C05EMHTG6FM/p1709641955657309)
Fixes #2501
=> chore: clean up webhookEvents table before adding & populating FKs

packages/auth/src/app.ts, packages/backend/src/app.ts
- tightening our security by not allowing introspection in production
- fixes #2416
=> chore: disable graphql introspection in production

package.json, packages/frontend/app/routes/_index.tsx
We don't want to publish the Rafiki packages on npm. Hence, the [version is optional](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#version). I propose removing it as long as all runs in docker.
=> chore: remove version from monorepo package.json

packages/frontend/app/entry.server.tsx
I think this is my first frontend PR ever 😂
Adds X-Frame-Options header to Admin UI. 
- fixes #2418
=> chore(frontend): add X-Frame-Options header

bruno/collections/Rafiki/Examples/Open Payments/Continuation Request.bru, bruno/collections/Rafiki/Examples/Open Payments/Create Incoming Payment.bru, bruno/collections/Rafiki/Examples/Open Payments/Create Outgoing Payment.bru, bruno/collections/Rafiki/Examples/Open Payments/Create Quote.bru, bruno/collections/Rafiki/Examples/Open Payments/Grant Request Outgoing Payment.bru, localenv/README.md, openapi/auth-server.yaml, openapi/schemas.yaml, packages/documentation/src/content/docs/playground/overview.md, scripts/fetch-schemas.sh
- updates OP schemas
- uses polling instead of `interact_ref`
- fixes #2519
=> feat(bruno): use polling in grant continuation

packages/auth/jest.setup.js
- adds healtheck to auth test db startup (same as backend)
- fixes https://github.com/interledger/rafiki/issues/2604
=> fix(auth): add healthcheck to solve occasional ci failure

bruno/collections/Rafiki/Open Payments APIs/Incoming Payments/Complete Incoming Payment.bru, bruno/collections/Rafiki/Open Payments APIs/Incoming Payments/Create Incoming Payment.bru, bruno/collections/Rafiki/Open Payments APIs/Incoming Payments/Get Incoming Payment -Unauthenticated-.bru, bruno/collections/Rafiki/Open Payments APIs/Incoming Payments/Get Incoming Payment.bru, bruno/collections/Rafiki/Open Payments APIs/Incoming Payments/List Incoming Payments.bru, bruno/collections/Rafiki/Open Payments APIs/Outgoing Payments/Create Outgoing Payment.bru, bruno/collections/Rafiki/Open Payments APIs/Outgoing Payments/Get Outgoing Payment.bru, bruno/collections/Rafiki/Open Payments APIs/Outgoing Payments/List Outgoing Payments.bru, bruno/collections/Rafiki/Open Payments APIs/Quotes/Create Quote.bru, bruno/collections/Rafiki/Open Payments APIs/Quotes/Get Quote.bru, bruno/collections/Rafiki/Open Payments APIs/Wallet Address/Get Wallet Address Keys.bru, bruno/collections/Rafiki/Open Payments APIs/Wallet Address/Get a Wallet Address.bru, bruno/collections/Rafiki/Open Payments Auth APIs/Grants/Continuation Request.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Peer.bru
There were still some leftover postman scripts that were commented out in the bruno files. I replaced them with the proper bruno scripts.
=> chore: clean up bruno scripts and tests

infrastructure/helm/tigerbeetle/values.yaml, localenv/tigerbeetle/docker-compose.yml, packages/backend/package.json, packages/backend/src/tests/tigerbeetle.ts, pnpm-lock.yaml
https://github.com/interledger/rafiki/issues/1438
- Upgraded to the production release of TigerBeetle, `v0.15.3`
=> feat(1438): update tigerbeetle to latest release.

packages/backend/src/webhook/service.test.ts, packages/backend/src/webhook/service.ts
=> fix(webhook): move max retry check in query

.github/workflows/node-build.yml
- Schedule nightly build at 21:00
- separate multi-platform builds due to docker buildx not having support for saving and loading multiplatform builds
improve existing workflow
fixes #2651
=> feat(workflows): improve existing pipeling and schedule nightly builds

test/integration/integration.test.ts, test/integration/scripts/run-tests.sh
- `run-tests.sh` now exits correctly (according to the jest test exit code). verified by:
- tests pass and job succeeds: https://github.com/interledger/rafiki/actions/runs/8724045520/job/23933754003?pr=2669
- tests fail and job fails: https://github.com/interledger/rafiki/actions/runs/8724104129/job/23933945465?pr=2669
fixes: #2668
=> fix: exit run-tests.sh with test exit code

.github/workflows/node-build.yml
- Update timeout for docker build workflow job from 5 to 10 minutes
=> fix(workflows): change docker build timeout to 10min

packages/documentation/package.json, pnpm-lock.yaml
- This PR bumps the documentation dependencies to the latest versions, notably the `astro-graphql-plugin` (https://github.com/interledger/astro-graphql-plugin), which needed a desperate update but nobody got around to it
Closes #2293
=> chore: bump docs dependencies to the latest versions

.github/CODEOWNERS, .github/labeler.yml
- Removing CODEOWNERS file, to not tag our tech writers when documentation change happens
- add `type: documentation` label only when md files are changed in the documentation package
Fixes #2616
=> chore: update codeowners & labeler

packages/documentation/package.json, pnpm-lock.yaml
- This PR bumps dependencies to the latest version, including the [0.22.0](https://github.com/withastro/starlight/blob/main/packages/starlight/CHANGELOG.md#0220) version of Starlight that includes synced tabs. Reviewed the changelog and the potential breaking changes do not affect our implementation.
Related to https://github.com/interledger/open-payments/issues/352
=> chore: bump dependencies to latest versions

bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Cross Currency Payment/Create Quote.bru, bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Payment/Create Quote.bru, bruno/collections/Rafiki/environments/Local Playground.bru, bruno/collections/Rafiki/scripts.js, localenv/README.md, localenv/happy-life-bank/seed.yml, packages/documentation/src/content/docs/playground/overview.md
- Fix `createQuote` requests in Peer to Peer bruno examples by adding `signature` header
- Tidy up bruno scripts
- Fix broken link in doc
Fixes #2700
=> chore(bruno): fix Peer to Peer example requests

packages/auth/src/app.ts, packages/auth/src/graphql/errors/index.ts, packages/auth/src/graphql/generated/graphql.schema.json, packages/auth/src/graphql/generated/graphql.ts, packages/auth/src/graphql/plugin/index.ts, packages/auth/src/graphql/resolvers/grant.test.ts, packages/auth/src/graphql/resolvers/grant.ts, packages/auth/src/graphql/schema.graphql
- Adds logs to the admin graphql resolvers in the auth server.
Fixes #2574.
Based largely off of https://github.com/interledger/rafiki/pull/2667. Thanks @sabineschaller!
=> feat(auth)!: add logs to graphql resolvers

packages/documentation/src/content/docs/reference/get-involved.md
=> docs: add get involved page

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml, localenv/mock-account-servicing-entity/app/lib/apiClient.ts, localenv/mock-account-servicing-entity/app/lib/parse_config.server.ts, localenv/mock-account-servicing-entity/app/routes/consent-screen.tsx, localenv/mock-account-servicing-entity/app/routes/mock-idp._index.tsx, localenv/mock-account-servicing-entity/app/routes/shoe-shop.tsx, packages/mock-account-service-lib/src/types.ts, test/integration/lib/config.ts, test/integration/lib/test-actions/index.ts, test/integration/testenv/cloud-nine-wallet/.env, test/integration/testenv/cloud-nine-wallet/docker-compose.yml, test/integration/testenv/happy-life-bank/.env
- updates `x-idp-secret` header in `mock-account-servicing-entity` to fix interact bug
fixes https://github.com/interledger/rafiki/issues/2745
=> fix(mock-ase): interact bug by updating idp secret

localenv/README.md, localenv/mock-account-servicing-entity/app/lib/apiClient.ts, localenv/mock-account-servicing-entity/app/routes/consent-screen.tsx, localenv/mock-account-servicing-entity/app/routes/mock-idp._index.tsx, localenv/mock-account-servicing-entity/app/routes/shoe-shop.tsx
- Since the MASE is a mock environment we handle the idpSecret insecurely. We want to ensure any potential implementers are aware that our MASE is not intended as a reference architecture.
=> chore: added disclaimer comments around our implementation of the MASE

packages/auth/package.json, packages/backend/package.json, packages/token-introspection/package.json, pnpm-lock.yaml, test/integration/package.json
a fix for this renovate upgrade https://github.com/interledger/rafiki/pull/2715
=> chore: upgrade open-payments

bruno/collections/Rafiki/Sample Webhook Events/Asset Liquidity Low.bru, bruno/collections/Rafiki/Sample Webhook Events/Incoming Payment Completed.bru, bruno/collections/Rafiki/Sample Webhook Events/Incoming Payment Created.bru, bruno/collections/Rafiki/Sample Webhook Events/Incoming Payment Expired.bru, bruno/collections/Rafiki/Sample Webhook Events/Outgoing Payment Completed.bru, bruno/collections/Rafiki/Sample Webhook Events/Outgoing Payment Created.bru, bruno/collections/Rafiki/Sample Webhook Events/Outgoing Payment Failed.bru, bruno/collections/Rafiki/Sample Webhook Events/Peer Liquidity Low.bru, bruno/collections/Rafiki/Sample Webhook Events/Wallet Address Not Found.bru, bruno/collections/Rafiki/Sample Webhook Events/Wallet Address Web Monetization.bru, bruno/collections/Rafiki/environments/Local Playground.bru, packages/documentation/astro.config.mjs, packages/documentation/src/content/docs/concepts/accounting/accounts-and-transfers.md, packages/documentation/src/content/docs/integration/getting-started.md, packages/documentation/src/content/docs/integration/webhook-events.mdx
After starting work on issue 
- #2465
we realized that instead of adding custom retry behavior for any of our webhook requets, we should keep the simple retry mechanism of "retry as long as we don't get back a 200 response", and update the documentation for webhook events in general.
This change:
- Renames "Event Handlers" page to "Webhook Events"
- Moves over "event types" table from the "Getting Started" page to the "Webhook Events" page
- Adds additional sections to the "Webhook Events" page: Setup, Errors, and Best Practices
- Adds sample bruno requests for the webhook listener, to give integrators an easy way to see the webhook payload and test the integration manually
Fixes #2761
=> docs: update webhook event documentation

packages/frontend/app/lib/validate.server.ts, packages/frontend/app/routes/payments._index.tsx, packages/frontend/app/routes/wallet-addresses.$walletAddressId.tsx
- Implemented filtering of payments based on walletAddressId.
- Maintained other filter parameters (e.g., type, pagination) when updating walletAddressId.
- Included a button in the wallet Address page to navigate directly to view the payments page filtering for that wallet's address ID.
- fixes #2689
- fixes ##2758
=> feat: filter payments per wallet address ID

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml, packages/frontend/README.md, packages/frontend/app/lib/envConfig.server.ts
- fixed typo in KRATOS_CONTAINER_PULIC_URL
=> fix!: typo in KRATOS_CONTAINER_PULIC_URL

packages/backend/src/app.ts, packages/backend/src/config/app.ts, packages/backend/src/shared/utils.test.ts, packages/backend/src/shared/utils.ts, packages/backend/src/tests/apiSignature.ts, packages/backend/src/tests/app.ts, packages/backend/src/tests/context.ts
- Admin API signature validation now caches signatures in redis and limits how late a signature may be used so that those same signatures cannot be reused for subsequent requests.
Fixes #2725.
=> feat(backend): secure admin api from replay attacks

bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Cross Currency Payment/Create Outgoing Payment.bru, bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Cross Currency Payment/Create Quote.bru, bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Cross Currency Payment/Create Receiver (remote Incoming Payment).bru, bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Payment/Create Outgoing Payment.bru, bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Payment/Create Quote.bru, bruno/collections/Rafiki/Examples/Admin API -  only locally/Peer-to-Peer Payment/Create Receiver -remote Incoming Payment-.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Asset.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Incoming Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Or Update Peer By Url.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Outgoing Payment From Incoming Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Outgoing Payment.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Peer.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Quote.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Receiver (remote Incoming Payment).bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Wallet Address Key.bru, bruno/collections/Rafiki/Rafiki Admin APIs/Create Wallet Address.bru, bruno/collections/Rafiki/environments/Autopeering.bru, localenv/mock-account-servicing-entity/app/lib/requesters.ts
- Adds variables to the Autopeering bruno env collection to make Admin API requests work
- Fixes incorrect createWalletAddressKey request in the MASE 
- In Admin API Bruno request, checks for data before setting the variable. Without this, we end up "hiding" the actual error that came from the backend:
Before:
After:
Fixes #2812
=> chore: update autopeering bruno environment, fix MASE request

localenv/telemetry/grafana/provisioning/dashboards/example.json, packages/backend/src/index.ts, packages/backend/src/payment-method/ilp/service.ts
- adds `ilp_rate_probe_time_ms` histogram metric and visualization to the local grafana example dashboard
fixes: #2801
=> feat(backend): add rate probe metric

packages/documentation/src/content/docs/services-and-aux-packages/auth-service.mdx
=> testing collab on sarah's branch

packages/documentation/src/content/docs/intro-to-rafiki/overview.mdx
=> docs: testing update

packages/backend/src/open_payments/wallet_address/model.ts, packages/backend/src/open_payments/wallet_address/routes.test.ts
- Do not expose all the additional properties field, but just key and value
fixes #2874
=> fix(wallet-address)!: additional properties

.github/workflows/add_to_docs_board.yml
- Workflow to add issues to project boards automatically when labelled with `docs`
Fixes #2912
=> feat(workflow): add to docs project if issue is labelled with docs

.github/workflows/add_to_docs_board.yml
- Update add to project action version to correct one
=> chore(workflow): fix add to project action version

bruno/collections/Rafiki/Rafiki Admin APIs/Update Incoming Payment.bru
- Change to name of response in bruno to delete error in Validation GRAPHQL
=> test update change response to fix error of validatin graphql

packages/documentation/astro.config.mjs
- This moves the autogenerated api docs into the integration section.
- To see the changes locally, run `pnpm --filter documentation build:docs`
=> chore: included the api docs in the integration section

.prettierignore
=> chore: disable prettier in docs package for markdown table readability

packages/documentation/src/content/docs/integration/peering.mdx, packages/documentation/src/content/docs/integration/services/backend-service.mdx, packages/documentation/src/content/docs/overview/concepts/interledger.mdx, packages/frontend/app/routes/peers.$peerId.tsx, packages/frontend/app/routes/peers.create.tsx
Also deleted blank peering.mdx page
=> docs: fixes #2962

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/schema.graphql, packages/frontend/app/generated/graphql.ts, packages/mock-account-service-lib/src/generated/graphql.ts, test/integration/lib/generated/graphql.ts
Updated descriptions for the Backend Admin API. This fixes https://github.com/interledger/rafiki/issues/3004
While these changes are enhancements to the current reference docs, I understand that the graphql schemas are also used to generate other files/types.
=> docs: update graphql descriptions backend

packages/auth/src/graphql/generated/graphql.ts, packages/auth/src/graphql/schema.graphql
- Fix auth graphql generated types and formatting that's currently on `main`
=> chore(auth): fix generated types

localenv/README.md, packages/documentation/src/content/docs/integration/playground/autopeering.mdx, packages/documentation/src/content/docs/integration/playground/overview.mdx
Created to fix #3052, which is in response to #3050.
@oana-lolea I wasn't sure if every reference to `--volumes` should come out or only specific ones. Please take a look and let me know if I need to change anything!
=> docs: fixes #3052

packages/documentation/astro.config.mjs, packages/documentation/package.json, pnpm-lock.yaml
- Docs dependency updates
- Will enable use of Link Buttons component
=> chore: routine dependency bumps

packages/documentation/src/content/docs/resources/glossary.mdx
=> docs: 2976/glossary

packages/documentation/astro.config.mjs, packages/documentation/src/components/PageSidebar.astro
- Removing the sidebar `Overview` item on the Rafiki docs glossary page.
=> chore: removed Glossary page's overview section

packages/documentation/astro.config.mjs, packages/documentation/src/content/docs/index.mdx
- Added an Umami site tracking script so that we can record page visits for the Rafiki docs.
This gets the basic infrastructure in place and allows us to track page views. There will be more work needed to add granular event tracking based on clicking links.
=> feat: added basic site tracking using Umami

packages/documentation/src/content/docs/integration/requirements/assets.mdx, packages/documentation/src/content/docs/integration/requirements/sending-fees.mdx, packages/documentation/src/content/docs/integration/requirements/wallet-addresses.mdx
=> docs: mi/3169/remove-rafiki-admin-references

pnpm-lock.yaml, test/performance/README.md, test/performance/package.json, test/performance/scripts/create-outgoing-payments.js, test/performance/src/json-canonicalize.js, test/performance/webpack.config.js
- signs similarly to apollo clients
- adds json-canonicalize module and webpack to build it for k6
=> fix(performance): add signature header to fix 401

packages/documentation/src/content/docs/integration/playground/overview.mdx
Added sequence diagram for interacting with OP API using Bruno
Fixes https://github.com/interledger/rafiki/issues/3242
=> docs: adding sequence diagram to local playground page

localenv/mock-account-servicing-entity/app/lib/utils.ts
fixes issue on getting OPEN_PAYMENTS env value from process in the frontend
Changed the way env is retrieved
fixes #3246
=> fix(mock-ase): process is undefined error in client

packages/documentation/astro.config.mjs, packages/documentation/src/content/docs/integration/requirements/overview.mdx, packages/documentation/src/content/docs/overview/concepts/account-servicing-entity.mdx, packages/documentation/src/content/docs/overview/overview.mdx
=> docs: ase and playground related updates

packages/documentation/astro.config.mjs, packages/documentation/src/components/PageSidebar.astro, packages/documentation/src/content/docs/overview/concepts/interledger.mdx, packages/documentation/src/content/docs/overview/concepts/payment-pointers.mdx
=> docs: add payment pointer/wallet address concepts page

packages/documentation/src/content/docs/integration/deployment/services/backend-service.mdx, packages/documentation/src/content/docs/integration/requirements/peers.mdx, packages/documentation/src/content/docs/overview/concepts/interledger.mdx
- Reorient Prerequisites list on Peers page into sections
- Added context for authTokens
=> docs: mi/3294/peers-update

localenv/mock-account-servicing-entity/package.json, packages/frontend/package.json, pnpm-lock.yaml
- Updated remix packages in `frontend` and `mase` to fix CVE-2025-31137 [vulnerability](https://github.com/remix-run/react-router/security/advisories/GHSA-4q56-crqp-v477)
Fixes  #3377
=> chore: update remix packages to fix vulnerability 

packages/documentation/src/components/Header.astro, packages/documentation/src/components/PageSidebar.astro
Just including the back dated breaking changes here
=> chore: docs dependency bumps

packages/documentation/src/content/docs/integration/playground/overview.mdx, packages/documentation/src/content/docs/integration/requirements/assets.mdx, packages/documentation/src/content/docs/integration/requirements/exchange-rates.mdx, packages/documentation/src/content/docs/integration/requirements/open-payments/grants-revoking.mdx, packages/documentation/src/content/docs/integration/requirements/open-payments/idp.mdx, packages/documentation/src/content/docs/integration/requirements/sending-fees.mdx, packages/documentation/src/content/docs/integration/requirements/webhook-events.mdx, packages/documentation/src/content/docs/overview/concepts/accounting.mdx
Also removed Mermaid/Wrapper from import on pages not using Mermaid
=> docs: fixes #3388

packages/documentation/astro.config.mjs, packages/documentation/src/components/PageSidebar.astro, packages/documentation/src/content/docs/overview/concepts/clearing-settlement.mdx
Adds a page for Clearing and Settlement
=> docs: fixes #3382

packages/backend/src/open_payments/wallet_address/middleware.test.ts, packages/backend/src/open_payments/wallet_address/middleware.ts
- improves redirect url
- encodes wallet address
fixes #3396
=> feat(backend): improved redirect url for wallet address

packages/documentation/src/content/docs/resources/get-involved.mdx
=> docs: mi/3333/get-involved

packages/documentation/package.json, pnpm-lock.yaml
- This PR bumps dependencies to the latest versions, including the docs-design-system with an updated MermaidWrapper component (see https://github.com/interledger/docs-design-system/releases/tag/v0.8.0)
=> docs: bump docs dependencies to their latest versions

packages/documentation/astro.config.mjs, packages/documentation/src/components/Header.astro, packages/documentation/src/content/docs/es/index.mdx, packages/documentation/src/content/docs/es/overview/concepts/account-servicing-entity.mdx, packages/documentation/src/content/docs/es/overview/concepts/accounting.mdx, packages/documentation/src/content/docs/es/overview/concepts/clearing-settlement.mdx, packages/documentation/src/content/docs/es/overview/concepts/interledger.mdx, packages/documentation/src/content/docs/es/overview/concepts/open-payments.mdx, packages/documentation/src/content/docs/es/overview/concepts/payment-pointers.mdx, packages/documentation/src/content/docs/es/overview/concepts/telemetry.mdx, packages/documentation/src/content/docs/es/overview/overview.mdx
- This PR configures Starlight for Spanish content and scaffolds the identified pages for translation to be served from /es
=> feat: setup i18n for rafiki docs

localenv/cloud-nine-wallet/docker-compose.yml, localenv/happy-life-bank/docker-compose.yml
=> fix(localenv): add required env vars to docker-compose

packages/point-of-sale/migrations/20250708121812_create_pos_device_table.js, packages/point-of-sale/src/index.ts, packages/point-of-sale/src/merchant/devices/errors.ts, packages/point-of-sale/src/merchant/devices/model.ts, packages/point-of-sale/src/merchant/devices/service.test.ts, packages/point-of-sale/src/merchant/devices/service.ts
- Created POS Device service
- Changed POS Device to use a walletAddressUrl instead of its id and updated its migration
- Changed POS Device `keyId` to be nonNullable and unique because it will be generated on creation
- Added function that generates `keyId` based on the following structure: 
`pos:<first 6 chars from the deviceName (without whitespaces)><random 6 chars (using uuid)>` 
and added a test for it
Fixes #3486
=> feat(point-of-sale): POS Device service

scripts/localenv-tunnel-setup.js
=> fix: update default autopeer link to testnet

packages/point-of-sale/package.json, packages/point-of-sale/src/index.ts, packages/point-of-sale/src/payments/service.test.ts, packages/point-of-sale/src/payments/service.ts, pnpm-lock.yaml
- Added `axios` to package
- Created an axios get request to obtain wallet address details, since we need the url of the `card-service` to initiate the payment 
Fixes #3559
=> feat(point-of-sale): service for obtaining walletAddress by its url from Rafiki Backend

packages/backend/src/open_payments/payment/incoming/service.test.ts, packages/mock-account-service-lib/src/seed.ts
- Fix MASE seed script by making sure that we adding liquidity only for new peers & assets, avoiding multiple liquidity deposits when the seed script re-tries
- Additional logging/error checks in script
- Update flaky test
Discovered during multi-hop (RAF-1063) testing
=> fix(masl): seed script in MASE

localenv/mock-account-servicing-entity/generated/graphql.ts, packages/backend/src/graphql/generated/graphql.schema.json, packages/backend/src/graphql/generated/graphql.ts, packages/backend/src/graphql/resolvers/tenant_settings.test.ts, packages/backend/src/graphql/resolvers/tenant_settings.ts, packages/backend/src/graphql/schema.graphql, packages/backend/src/tenants/service.test.ts, packages/backend/src/tenants/service.ts, packages/backend/src/tenants/settings/service.test.ts, packages/frontend/app/generated/graphql.ts, packages/frontend/app/lib/validate.server.ts, packages/frontend/app/routes/tenants.create.tsx, packages/mock-account-service-lib/src/generated/graphql.ts, packages/mock-account-service-lib/src/requesters.ts, test/test-lib/src/generated/graphql.ts
- Adds input fields for tenant settings in Admin UI.
Closes RAF-1077.
=> feat(frontend): tenant settings fields for tenant create

packages/frontend/app/generated/graphql.ts, packages/frontend/app/lib/api/tenant.server.ts, packages/frontend/app/lib/validate.server.ts, packages/frontend/app/routes/wallet-addresses._index.tsx, packages/frontend/app/routes/wallet-addresses.create.tsx
- Updates Rafiki Admin UI to use the correct tenant's Wallet Address Prefix in the addon for the wallet address name.
Closes RAF-1075. Closes #3466.
=> feat(frontend): use tenant wallet address prefix in admin UI

bruno/collections/Rafiki/Examples/Open Payments/Get receiver wallet address.bru, bruno/collections/Rafiki/Examples/Open Payments/Get sender wallet address.bru, bruno/collections/Rafiki/environments/Local Playground.bru, bruno/collections/Rafiki/environments/Tenanted Local Playground - Swapped Sender & Receiver.bru, localenv/mock-account-servicing-entity/app/lib/parse_config.server.ts, packages/mock-account-service-lib/src/requesters.ts, packages/mock-account-service-lib/src/seed.ts
- Fixes a typo in the default environment config for `backend`.
- Fixes a pre-request-script when resolving wallet addresses in the Bruno examples.
- Fixes an issue where a tenanted peer would not be seeded if it was specified in the seed file.
Fixes RAF-1143.
=> fix(localenv): fix env, localenv, bruno errors

packages/documentation/astro.config.mjs, packages/documentation/src/components/Footer.astro, packages/documentation/src/styles/rafiki.css
Add footer to Rafiki Docs linking to the Interledger Foundation homepage.
=> docs: add footer

.github/PULL_REQUEST_TEMPLATE/doc_template.md, .github/PULL_REQUEST_TEMPLATE/eng_template.md, .github/pull_request_template.md
Added PR template for doc team, moved default eng PR to its own template
=> docs: add pr template for docs team
